#include "programs.h"
#include <string.h>

/* Compiled program arrays (generated by tasm.py -o .c)
 * For now, empty registry — programs added when compiled.
 */
const vm_program_t vm_programs[] = {
    {NULL, NULL, 0}  /* sentinel */
};
const size_t vm_program_count = 0;

const vm_program_t *vm_program_find(const char *name) {
    for (size_t i = 0; i < vm_program_count; i++) {
        if (strcmp(vm_programs[i].name, name) == 0)
            return &vm_programs[i];
    }
    return NULL;
}
