/* Generated by tools/soc_scraper.py from tools/esp32c6.svd — do not edit.
 *
 * Reflex's own ESP32-C6 register constants, replacing the ESP-IDF
 * soc register headers. These are silicon facts rather than ESP-IDF code:
 * every address and bit position below is computed from the vendor SVD that
 * already backs the 12,738-node shadow atlas, so nothing here was copied by
 * hand from a vendor header where a typo would write to a real register.
 *
 * Equivalence with the ESP-IDF macros these replace is proved, not asserted:
 * `make soc-bridge` compiles a translation unit of _Static_asserts inside a
 * real ESP-IDF build. Regenerate with `make soc-header`.
 */
#ifndef REFLEX_SOC_ESP32C6_H
#define REFLEX_SOC_ESP32C6_H

#include <stdint.h>

/* LP_WDT.WDTCONFIG0 @ base+0x0 — stage actions, enable, pause-in-sleep */
#define REFLEX_LP_WDT_CONFIG0_REG 0x600B1C00u
/* LP_WDT.CONFIG1 @ base+0x4 — stage 0 timeout, in slow-clock ticks */
#define REFLEX_LP_WDT_CONFIG1_REG 0x600B1C04u
/* LP_WDT.WDTFEED @ base+0x14 */
#define REFLEX_LP_WDT_FEED_REG 0x600B1C14u
/* LP_WDT.INT_RAW @ base+0x24 — stage expiry, latched */
#define REFLEX_LP_WDT_INT_RAW_REG 0x600B1C24u
/* LP_WDT.INT_RAW.LP_WDT_INT_RAW bit 31 — set when stage 0 expires */
#define REFLEX_LP_WDT_INT_RAW_BIT 0x80000000u
/* LP_WDT.WDTWPROTECT @ base+0x18 — write the key here to unlock the rest */
#define REFLEX_LP_WDT_WPROTECT_REG 0x600B1C18u
/* LP_WDT.WDTCONFIG0.WDT_EN bit 31 */
#define REFLEX_LP_WDT_EN 0x80000000u
/* LP_WDT.WDTCONFIG0.WDT_PAUSE_IN_SLP bit 9 — set means the watchdog stops while asleep; the net
 * depends on it being clear */
#define REFLEX_LP_WDT_PAUSE_IN_SLP 0x00000200u
/* LP_WDT.WDTCONFIG0.WDT_PROCPU_RESET_EN bit 11 */
#define REFLEX_LP_WDT_PROCPU_RESET_EN 0x00000800u
/* LP_WDT.WDTCONFIG0.WDT_CHIP_RESET_EN bit 8 */
#define REFLEX_LP_WDT_CHIP_RESET_EN 0x00000100u
/* LP_WDT.SWD_CONF @ base+0x1C — super-watchdog config */
#define REFLEX_LP_WDT_SWD_CONFIG_REG 0x600B1C1Cu
/* LP_WDT.SWD_WPROTECT @ base+0x20 — super-watchdog write protect */
#define REFLEX_LP_WDT_SWD_WPROTECT_REG 0x600B1C20u
/* LP_WDT.SWD_CONF.SWD_AUTO_FEED_EN bit 18 */
#define REFLEX_LP_WDT_SWD_AUTO_FEED_EN 0x00040000u
/* LP_WDT.INT_ENA_RTC @ base+0x2C — IDF drops the _RTC suffix */
#define REFLEX_LP_WDT_INT_ENA_REG 0x600B1C2Cu
/* LP_WDT.INT_CLR_RTC @ base+0x30 — IDF drops the _RTC suffix */
#define REFLEX_LP_WDT_INT_CLR_REG 0x600B1C30u
/* LP_WDT.INT_ENA_RTC.WDT_INT_ENA bit 31 */
#define REFLEX_LP_WDT_LP_WDT_INT_ENA 0x80000000u
/* LP_WDT.INT_CLR_RTC.WDT_INT_CLR bit 31 */
#define REFLEX_LP_WDT_LP_WDT_INT_CLR 0x80000000u
/* LP_WDT.INT_ENA_RTC.SUPER_WDT_INT_ENA bit 30 */
#define REFLEX_LP_WDT_SUPER_WDT_INT_ENA 0x40000000u
/* LP_WDT.INT_CLR_RTC.SUPER_WDT_INT_CLR bit 30 */
#define REFLEX_LP_WDT_SUPER_WDT_INT_CLR 0x40000000u
/* TIMG0.WDTFEED @ base+0x60 — IDF indexes by group; Boot0 only uses group 0 */
#define REFLEX_TIMG0_WDTFEED_REG 0x60008060u
/* TIMG0.WDTWPROTECT @ base+0x64 */
#define REFLEX_TIMG0_WDTWPROTECT_REG 0x60008064u
/* TIMG0.WDTCONFIG0 @ base+0x48 */
#define REFLEX_TIMG0_WDTCONFIG0_REG 0x60008048u
/* TIMG1.WDTCONFIG0 @ base+0x48 */
#define REFLEX_TIMG1_WDTCONFIG0_REG 0x60009048u
/* TIMG1.WDTWPROTECT @ base+0x64 */
#define REFLEX_TIMG1_WDTWPROTECT_REG 0x60009064u
/* TIMG0.WDTCONFIG0.WDT_EN bit 31 — same bit in both groups */
#define REFLEX_TIMG_WDT_EN 0x80000000u
/* LP_AON.STORE0 @ base+0x0 — scratch, survives deep sleep */
#define REFLEX_LP_AON_STORE0_REG 0x600B1000u
/* LP_AON.SYS_CFG @ base+0x34 */
#define REFLEX_LP_AON_SYS_CFG_REG 0x600B1034u
/* LP_AON.SYS_CFG.HPSYS_SW_RESET bit 31 */
#define REFLEX_LP_AON_HPSYS_SW_RESET 0x80000000u
/* LP_ANA.LP_INT_ENA @ base+0x28 — SVD peripheral is LP_ANA */
#define REFLEX_LP_ANA_INT_ENA_REG 0x600B2C28u
/* LP_ANA.LP_INT_CLR @ base+0x2C */
#define REFLEX_LP_ANA_INT_CLR_REG 0x600B2C2Cu
/* LP_ANA.LP_INT_ENA.BOD_MODE0_LP_INT_ENA bit 31 */
#define REFLEX_LP_ANA_BOD_MODE0_INT_ENA 0x80000000u
/* LP_ANA.LP_INT_CLR.BOD_MODE0_LP_INT_CLR bit 31 */
#define REFLEX_LP_ANA_BOD_MODE0_INT_CLR 0x80000000u
/* PMU.HP_INT_ENA @ base+0x164 */
#define REFLEX_PMU_HP_INT_ENA_REG 0x600B0164u
/* PMU.HP_INT_ENA.SOC_WAKEUP_INT_ENA bit 31 */
#define REFLEX_PMU_SOC_WAKEUP_INT_ENA 0x80000000u
/* PMU.HP_INT_ENA.SOC_SLEEP_REJECT_INT_ENA bit 30 */
#define REFLEX_PMU_SOC_SLEEP_REJECT_INT_ENA 0x40000000u
/* ASSIST_DEBUG.CORE_0_RCD_EN @ base+0x44 */
#define REFLEX_ASSIST_DEBUG_CORE_0_RCD_EN_REG 0x600C2044u
/* ASSIST_DEBUG.CORE_0_RCD_EN.CORE_0_RCD_RECORDEN bit 0 */
#define REFLEX_ASSIST_DEBUG_CORE_0_RCD_RECORDEN 0x00000001u
/* ASSIST_DEBUG.CORE_0_RCD_EN.CORE_0_RCD_PDEBUGEN bit 1 */
#define REFLEX_ASSIST_DEBUG_CORE_0_RCD_PDEBUGEN 0x00000002u
/* ASSIST_DEBUG.CORE_0_MONTR_ENA @ base+0x0 — stack and area watchpoint enables; IDF calls this
 * INTR_ENA where the SVD says MONTR_ENA */
#define REFLEX_ASSIST_DEBUG_MONTR_ENA_REG 0x600C2000u
/* ASSIST_DEBUG.CORE_0_MONTR_ENA.CORE_0_SP_SPILL_MIN_ENA bit 8 */
#define REFLEX_ASSIST_DEBUG_SP_SPILL_MIN_ENA 0x00000100u
/* ASSIST_DEBUG.CORE_0_MONTR_ENA.CORE_0_SP_SPILL_MAX_ENA bit 9 */
#define REFLEX_ASSIST_DEBUG_SP_SPILL_MAX_ENA 0x00000200u
/* PCR.ASSIST_CONF @ base+0x100 */
#define REFLEX_PCR_ASSIST_CONF_REG 0x60096100u
/* PCR.ASSIST_CONF.ASSIST_CLK_EN bit 0 */
#define REFLEX_PCR_ASSIST_CLK_EN 0x00000001u
/* PCR.ASSIST_CONF.ASSIST_RST_EN bit 1 */
#define REFLEX_PCR_ASSIST_RST_EN 0x00000002u
/* EXTMEM.L1_CACHE_CTRL @ base+0x4 */
#define REFLEX_EXTMEM_L1_CACHE_CTRL_REG 0x600C8004u
/* EXTMEM.L1_CACHE_CTRL.L1_CACHE_SHUT_BUS0 bit 0 — IDF calls bus0 the IBUS */
#define REFLEX_EXTMEM_L1_CACHE_SHUT_IBUS 0x00000001u
/* EXTMEM.L1_CACHE_CTRL.L1_CACHE_SHUT_BUS1 bit 1 — IDF calls bus1 the DBUS */
#define REFLEX_EXTMEM_L1_CACHE_SHUT_DBUS 0x00000002u
/* SPI0.SPI_MEM_MMU_ITEM_CONTENT @ base+0x37C — IDF indexes by SPI unit; Boot0 uses 0 */
#define REFLEX_SPI_MEM_MMU_ITEM_CONTENT_REG 0x6000237Cu
/* SPI0.SPI_MEM_MMU_ITEM_INDEX @ base+0x380 */
#define REFLEX_SPI_MEM_MMU_ITEM_INDEX_REG 0x60002380u
/* SPI0.SPI_MEM_MMU_POWER_CTRL @ base+0x384 */
#define REFLEX_SPI_MEM_MMU_POWER_CTRL_REG 0x60002384u
/* PMU.SLP_WAKEUP_STATUS0 @ base+0x140 — wakeup cause after deep sleep */
#define REFLEX_PMU_SLP_WAKEUP_STATUS0_REG 0x600B0140u
/* LP_AON.STORE1 @ base+0x4 — scratch shared with Boot0 across a sleep-as-reset */
#define REFLEX_LP_AON_STORE1_REG 0x600B1004u
/* SYSTIMER base — peripheral base, not a register */
#define REFLEX_DR_REG_SYSTIMER_BASE 0x6000A000u
/* SYSTIMER.UNIT0_OP @ base+0x4 — value-latch handshake */
#define REFLEX_SYSTIMER_UNIT0_OP_REG 0x6000A004u
/* SYSTIMER.UNIT0_VALUE_LO @ base+0x44 — low half of the latched count */
#define REFLEX_SYSTIMER_UNIT0_VALUE_LO_REG 0x6000A044u
/* SYSTIMER.UNIT0_OP.TIMER_UNIT0_UPDATE bit 30 — write to latch */
#define REFLEX_SYSTIMER_UNIT0_UPDATE 0x40000000u
/* SYSTIMER.UNIT0_OP.TIMER_UNIT0_VALUE_VALID bit 29 — poll until latched */
#define REFLEX_SYSTIMER_UNIT0_VALUE_VALID 0x20000000u
/* MODEM_SYSCON base — peripheral base */
#define REFLEX_DR_REG_MODEM_SYSCON_BASE 0x600A9800u
/* MODEM_LPCON base — peripheral base */
#define REFLEX_DR_REG_MODEM_LPCON_BASE 0x600AF000u
/* MODEM_SYSCON.CLK_CONF @ base+0x4 */
#define REFLEX_MODEM_SYSCON_CLK_CONF_REG 0x600A9804u
/* MODEM_SYSCON.CLK_CONF1 @ base+0x14 */
#define REFLEX_MODEM_SYSCON_CLK_CONF1_REG 0x600A9814u
/* MODEM_SYSCON.MODEM_RST_CONF @ base+0x10 */
#define REFLEX_MODEM_SYSCON_RST_CONF_REG 0x600A9810u
/* MODEM_LPCON.CLK_CONF @ base+0x18 */
#define REFLEX_MODEM_LPCON_CLK_CONF_REG 0x600AF018u
/* MODEM_SYSCON.CLK_CONF.CLK_ZB_APB_EN bit 23 — 802.15.4 MAC APB clock */
#define REFLEX_MODEM_CLK_ZB_APB_EN 0x00800000u
/* MODEM_SYSCON.CLK_CONF.CLK_ZB_MAC_EN bit 24 — 802.15.4 MAC clock */
#define REFLEX_MODEM_CLK_ZB_MAC_EN 0x01000000u
/* MODEM_SYSCON.CLK_CONF.CLK_ETM_EN bit 22 */
#define REFLEX_MODEM_CLK_ETM_EN 0x00400000u
/* MODEM_SYSCON.CLK_CONF1.CLK_BT_APB_EN bit 17 — BT/802.15.4 common baseband APB clock */
#define REFLEX_MODEM_CLK_BT_APB_EN 0x00020000u
/* MODEM_SYSCON.CLK_CONF1.CLK_BT_EN bit 18 — BT/802.15.4 common baseband clock */
#define REFLEX_MODEM_CLK_BT_EN 0x00040000u
/* MODEM_SYSCON.MODEM_RST_CONF.RST_ZBMAC bit 24 — pulsed 1 then 0 to reset the MAC */
#define REFLEX_MODEM_RST_ZBMAC 0x01000000u
/* MODEM_LPCON.CLK_CONF.CLK_COEX_EN bit 1 — coexistence arbiter clock */
#define REFLEX_MODEM_LPCON_CLK_COEX_EN 0x00000002u
/* MODEM_SYSCON.CLK_CONF1.CLK_FE_APB_EN bit 16 — front-end APB clock */
#define REFLEX_MODEM_CLK_FE_APB_EN 0x00010000u
/* MODEM_SYSCON.CLK_CONF1.CLK_FE_80M_EN bit 13 */
#define REFLEX_MODEM_CLK_FE_80M_EN 0x00002000u
/* MODEM_SYSCON.CLK_CONF1.CLK_FE_160M_EN bit 14 */
#define REFLEX_MODEM_CLK_FE_160M_EN 0x00004000u
/* MODEM_SYSCON.CLK_CONF1.CLK_FE_CAL_160M_EN bit 15 */
#define REFLEX_MODEM_CLK_FE_CAL_160M_EN 0x00008000u
/* MODEM_LPCON.CLK_CONF.CLK_I2C_MST_EN bit 2 — analog register bus; PHY calibration writes through
 * it */
#define REFLEX_MODEM_LPCON_CLK_I2C_MST_EN 0x00000004u
/* MODEM_SYSCON.CLK_CONF_POWER_ST @ base+0xC */
#define REFLEX_MODEM_SYSCON_CLK_POWER_ST_REG 0x600A980Cu
/* MODEM_LPCON.CLK_CONF_POWER_ST @ base+0x20 */
#define REFLEX_MODEM_LPCON_CLK_POWER_ST_REG 0x600AF020u
/* IEEE802154 base — peripheral base, not a register */
#define REFLEX_DR_REG_IEEE802154_BASE 0x600A3000u
/* IEEE802154.COMMAND @ base+0x0 — TX/RX/stop commands */
#define REFLEX_154_COMMAND_REG 0x600A3000u
/* IEEE802154.CTRL_CFG @ base+0x4 — promiscuous, auto-ACK, coordinator */
#define REFLEX_154_CTRL_CFG_REG 0x600A3004u
/* IEEE802154.CHANNEL @ base+0x48 — frequency index, not channel: (ch-11)*5+3 */
#define REFLEX_154_CHANNEL_REG 0x600A3048u
/* IEEE802154.TX_POWER @ base+0x4C */
#define REFLEX_154_TX_POWER_REG 0x600A304Cu
/* IEEE802154.INF0_SHORT_ADDR @ base+0x8 — PAN info bank 0 is the one a single-PAN node uses */
#define REFLEX_154_INF0_SHORT_ADDR_REG 0x600A3008u
/* IEEE802154.INF0_PAN_ID @ base+0xC */
#define REFLEX_154_INF0_PAN_ID_REG 0x600A300Cu
/* IEEE802154.EVENT_EN @ base+0x60 — which events raise the interrupt */
#define REFLEX_154_EVENT_EN_REG 0x600A3060u
/* IEEE802154.EVENT_STATUS @ base+0x64 — write-1-to-clear */
#define REFLEX_154_EVENT_STATUS_REG 0x600A3064u
/* IEEE802154.TXDMA_ADDR @ base+0xD0 — pointer to the frame to send */
#define REFLEX_154_TXDMA_ADDR_REG 0x600A30D0u
/* IEEE802154.RXDMA_ADDR @ base+0xE0 — pointer to the receive buffer */
#define REFLEX_154_RXDMA_ADDR_REG 0x600A30E0u
/* IEEE802154.RX_STATUS @ base+0x80 */
#define REFLEX_154_RX_STATUS_REG 0x600A3080u
/* IEEE802154.TX_STATUS @ base+0x84 */
#define REFLEX_154_TX_STATUS_REG 0x600A3084u
/* IEEE802154.ED_SCAN_DURATION @ base+0x50 — written by mac_init */
#define REFLEX_154_ED_SCAN_DURATION_REG 0x600A3050u
/* IEEE802154.ED_SCAN_CFG @ base+0x54 — ED sample mode, set by mac_init */
#define REFLEX_154_ED_SCAN_CFG_REG 0x600A3054u
/* IEEE802154.RX_ABORT_INTR_CTRL @ base+0x68 — which rx aborts raise an event */
#define REFLEX_154_RX_ABORT_INTR_CTRL_REG 0x600A3068u
/* IEEE802154.ACK_FRAME_PENDING_EN @ base+0x6C */
#define REFLEX_154_ACK_FRAME_PENDING_EN_REG 0x600A306Cu
/* IEEE802154.COEX_PTI @ base+0x70 — coexistence traffic priority; RX dies without it */
#define REFLEX_154_COEX_PTI_REG 0x600A3070u
/* IEEE802154.COEX_PTI.CLOSE_RF_SEL bit 8 — the only other defined bit of COEX_PTI */
#define REFLEX_154_CLOSE_RF_SEL 0x00000100u
/* IEEE802154.TX_ABORT_INTERRUPT_CONTROL @ base+0x78 */
#define REFLEX_154_TX_ABORT_INTR_CTRL_REG 0x600A3078u
/* IEEE802154.ENHANCE_ACK_CFG @ base+0x7C */
#define REFLEX_154_ENHANCE_ACK_CFG_REG 0x600A307Cu
/* IEEE802154.SEC_CTRL @ base+0x128 — touched by the transmit path even unused */
#define REFLEX_154_SEC_CTRL_REG 0x600A3128u
/* IEEE802154.CTRL_CFG.HW_AUTO_ACK_TX_EN bit 0 */
#define REFLEX_154_CFG_AUTO_ACK_TX 0x00000001u
/* IEEE802154.CTRL_CFG.HW_AUTO_ACK_RX_EN bit 3 */
#define REFLEX_154_CFG_AUTO_ACK_RX 0x00000008u
/* IEEE802154.CTRL_CFG.HW_ENHANCE_ACK_TX_EN bit 1 — set in the reset state; Reflex implements no ACK
 */
#define REFLEX_154_CFG_ENHANCE_ACK_TX 0x00000002u
/* IEEE802154.CTRL_CFG.PAN_COORDINATOR bit 6 */
#define REFLEX_154_CFG_PAN_COORDINATOR 0x00000040u
/* IEEE802154.CTRL_CFG.PROMISCUOUS_MODE bit 7 */
#define REFLEX_154_CFG_PROMISCUOUS 0x00000080u
/* IEEE802154.CTRL_CFG.NO_RSS_TRK_ENB bit 25 — set on a working radio */
#define REFLEX_154_CFG_NO_RSS_TRK 0x02000000u
/* IEEE802154.CTRL_CFG.RX_DONE_TRIGGER_IDLE bit 27 — clear = stay in receive after a frame */
#define REFLEX_154_CFG_RX_DONE_IDLE 0x08000000u
/* IEEE802154.CTRL_CFG.MAC_INF0_ENABLE bit 28 — address-filter bank 0 */
#define REFLEX_154_CFG_MAC_INF0_ENABLE 0x10000000u
/* USB_DEVICE base — peripheral base; SVD name is USB_DEVICE */
#define REFLEX_DR_REG_USB_SERIAL_JTAG_BASE 0x6000F000u
/* USB_DEVICE.EP1 @ base+0x0 — FIFO data register, both directions */
#define REFLEX_USJ_EP1_REG 0x6000F000u
/* USB_DEVICE.EP1_CONF @ base+0x4 */
#define REFLEX_USJ_EP1_CONF_REG 0x6000F004u
/* USB_DEVICE.INT_RAW @ base+0x8 */
#define REFLEX_USJ_INT_RAW_REG 0x6000F008u
/* USB_DEVICE.INT_ST @ base+0xC */
#define REFLEX_USJ_INT_ST_REG 0x6000F00Cu
/* USB_DEVICE.INT_ENA @ base+0x10 */
#define REFLEX_USJ_INT_ENA_REG 0x6000F010u
/* USB_DEVICE.INT_CLR @ base+0x14 */
#define REFLEX_USJ_INT_CLR_REG 0x6000F014u
/* USB_DEVICE.EP1_CONF.SERIAL_OUT_EP_DATA_AVAIL bit 2 — host-to-device byte waiting */
#define REFLEX_USJ_OUT_EP_DATA_AVAIL 0x00000004u
/* USB_DEVICE.INT_ENA.SERIAL_OUT_RECV_PKT_INT_ENA bit 2 — same bit across RAW/ST/ENA/CLR */
#define REFLEX_USJ_OUT_RECV_PKT_INT 0x00000004u
/* LEDC base — peripheral base, not a register */
#define REFLEX_DR_REG_LEDC_BASE 0x60007000u
/* LEDC.CH%s_CONF0 @ base+0x0 — channel 0 */
#define REFLEX_LEDC_CH0_CONF0_REG 0x60007000u
/* LEDC.CH%s_HPOINT @ base+0x4 */
#define REFLEX_LEDC_CH0_HPOINT_REG 0x60007004u
/* LEDC.CH%s_DUTY @ base+0x8 — duty is stored shifted left by 4 */
#define REFLEX_LEDC_CH0_DUTY_REG 0x60007008u
/* LEDC.CH%s_CONF1 @ base+0xC */
#define REFLEX_LEDC_CH0_CONF1_REG 0x6000700Cu
/* LEDC.TIMER%s_CONF @ base+0xA0 — timer 0 */
#define REFLEX_LEDC_TIMER0_CONF_REG 0x600070A0u
/* LEDC.CH%s_CONF0.SIG_OUT_EN bit 2 */
#define REFLEX_LEDC_SIG_OUT_EN 0x00000004u
/* LEDC.CH%s_CONF0.PARA_UP bit 4 — latch channel config */
#define REFLEX_LEDC_CH_PARA_UP 0x00000010u
/* LEDC.CH%s_CONF1.DUTY_START bit 31 */
#define REFLEX_LEDC_DUTY_START 0x80000000u
/* LEDC.TIMER%s_CONF.RST bit 24 — reads high out of reset */
#define REFLEX_LEDC_TIMER_RST 0x01000000u
/* LEDC.TIMER%s_CONF.PARA_UP bit 26 — latch timer config */
#define REFLEX_LEDC_TIMER_PARA_UP 0x04000000u
/* PCR.LEDC_CONF @ base+0x34 — peripheral clock and reset */
#define REFLEX_PCR_LEDC_CONF_REG 0x60096034u
/* PCR.LEDC_SCLK_CONF @ base+0x38 — source clock gate and select */
#define REFLEX_PCR_LEDC_SCLK_CONF_REG 0x60096038u
/* PCR.LEDC_CONF.LEDC_CLK_EN bit 0 */
#define REFLEX_PCR_LEDC_CLK_EN 0x00000001u
/* PCR.LEDC_CONF.LEDC_RST_EN bit 1 — asserted means held in reset */
#define REFLEX_PCR_LEDC_RST_EN 0x00000002u
/* PCR.LEDC_SCLK_CONF.LEDC_SCLK_EN bit 22 */
#define REFLEX_PCR_LEDC_SCLK_EN 0x00400000u
/* PCNT base — peripheral base, not a register */
#define REFLEX_DR_REG_PCNT_BASE 0x60012000u
/* PCNT.U%s_CONF0 @ base+0x0 — unit 0: filter and per-channel modes */
#define REFLEX_PCNT_U0_CONF0_REG 0x60012000u
/* PCNT.U%s_CONF1 @ base+0x4 — watch thresholds */
#define REFLEX_PCNT_U0_CONF1_REG 0x60012004u
/* PCNT.U%s_CONF2 @ base+0x8 — count limits */
#define REFLEX_PCNT_U0_CONF2_REG 0x60012008u
/* PCNT.U%s_CNT @ base+0x30 — the count itself */
#define REFLEX_PCNT_U0_CNT_REG 0x60012030u
/* PCNT.CTRL @ base+0x60 — reset and pause, all units */
#define REFLEX_PCNT_CTRL_REG 0x60012060u
/* PCNT.U%s_CONF0.FILTER_EN bit 10 — set out of reset */
#define REFLEX_PCNT_FILTER_EN 0x00000400u
/* PCNT.U%s_CONF0.THR_ZERO_EN bit 11 — watch events, all set out of reset */
#define REFLEX_PCNT_THR_ZERO_EN 0x00000800u
/* PCNT.U%s_CONF0.THR_H_LIM_EN bit 12 */
#define REFLEX_PCNT_THR_H_LIM_EN 0x00001000u
/* PCNT.U%s_CONF0.THR_L_LIM_EN bit 13 */
#define REFLEX_PCNT_THR_L_LIM_EN 0x00002000u
/* PCNT.U%s_CONF0.THR_THRES0_EN bit 14 */
#define REFLEX_PCNT_THR_THRES0_EN 0x00004000u
/* PCNT.U%s_CONF0.THR_THRES1_EN bit 15 */
#define REFLEX_PCNT_THR_THRES1_EN 0x00008000u
/* PCNT.CTRL.CNT_RST_U0 bit 0 — held asserted keeps the count at zero */
#define REFLEX_PCNT_CNT_RST_U0 0x00000001u
/* PCNT.CTRL.CNT_PAUSE_U0 bit 1 */
#define REFLEX_PCNT_CNT_PAUSE_U0 0x00000002u
/* PCR.PCNT_CONF @ base+0x94 — peripheral clock and reset */
#define REFLEX_PCR_PCNT_CONF_REG 0x60096094u
/* PCR.PCNT_CONF.PCNT_CLK_EN bit 0 */
#define REFLEX_PCR_PCNT_CLK_EN 0x00000001u
/* PCR.PCNT_CONF.PCNT_RST_EN bit 1 — asserted means held in reset */
#define REFLEX_PCR_PCNT_RST_EN 0x00000002u
/* RMT base — peripheral base, not a register */
#define REFLEX_DR_REG_RMT_BASE 0x60006000u
/* RMT.CH%s_TX_CONF0 @ base+0x10 — channel 0 transmit config */
#define REFLEX_RMT_CH0_TX_CONF0_REG 0x60006010u
/* RMT.CH%sDATA @ base+0x0 — the FIFO window onto channel memory */
#define REFLEX_RMT_CH0DATA_REG 0x60006000u
/* RMT.CH%s_TX_LIM @ base+0x58 */
#define REFLEX_RMT_CH0_TX_LIM_REG 0x60006058u
/* RMT.SYS_CONF @ base+0x68 — clock source and the FIFO/memory access mode; IDF doubles the prefix
 * on its SCLK fields (RMT_RMT_SCLK_*) */
#define REFLEX_RMT_SYS_CONF_REG 0x60006068u
/* RMT.INT_RAW @ base+0x38 */
#define REFLEX_RMT_INT_RAW_REG 0x60006038u
/* RMT.INT_CLR @ base+0x44 */
#define REFLEX_RMT_INT_CLR_REG 0x60006044u
/* RMT.CH%s_TX_CONF0.TX_START bit 0 */
#define REFLEX_RMT_TX_START 0x00000001u
/* RMT.CH%s_TX_CONF0.MEM_RD_RST bit 1 — rewind the read pointer */
#define REFLEX_RMT_MEM_RD_RST 0x00000002u
/* RMT.CH%s_TX_CONF0.APB_MEM_RST bit 2 — rewind the write pointer */
#define REFLEX_RMT_APB_MEM_RST 0x00000004u
/* RMT.CH%s_TX_CONF0.TX_STOP bit 7 */
#define REFLEX_RMT_TX_STOP 0x00000080u
/* RMT.CH%s_TX_CONF0.IDLE_OUT_EN bit 6 */
#define REFLEX_RMT_IDLE_OUT_EN 0x00000040u
/* RMT.CH%s_TX_CONF0.MEM_TX_WRAP_EN bit 4 */
#define REFLEX_RMT_MEM_TX_WRAP_EN 0x00000010u
/* RMT.CH%s_TX_CONF0.CARRIER_EFF_EN bit 20 — left set, as ESP-IDF leaves it; inert with the carrier
 * off */
#define REFLEX_RMT_CARRIER_EFF_EN 0x00100000u
/* RMT.CH%s_TX_CONF0.CARRIER_OUT_LV bit 22 */
#define REFLEX_RMT_CARRIER_OUT_LV 0x00400000u
/* RMT.CH%s_TX_LIM.LOOP_STOP_EN bit 21 */
#define REFLEX_RMT_LOOP_STOP_EN 0x00200000u
/* RMT.CH%s_TX_CONF0.CONF_UPDATE bit 24 — latch the channel config */
#define REFLEX_RMT_CONF_UPDATE 0x01000000u
/* RMT.SYS_CONF.APB_FIFO_MASK bit 0 — 1 addresses channel memory directly */
#define REFLEX_RMT_APB_FIFO_MASK 0x00000001u
/* RMT.SYS_CONF.SCLK_ACTIVE bit 26 */
#define REFLEX_RMT_SCLK_ACTIVE 0x04000000u
/* RMT.INT_RAW.CH%s_TX_END bit 0 — transmission complete */
#define REFLEX_RMT_CH0_TX_END_INT_RAW 0x00000001u
/* PCR.RMT_CONF @ base+0x2C — peripheral clock and reset */
#define REFLEX_PCR_RMT_CONF_REG 0x6009602Cu
/* PCR.RMT_SCLK_CONF @ base+0x30 */
#define REFLEX_PCR_RMT_SCLK_CONF_REG 0x60096030u
/* PCR.RMT_CONF.RMT_CLK_EN bit 0 */
#define REFLEX_PCR_RMT_CLK_EN 0x00000001u
/* PCR.RMT_CONF.RMT_RST_EN bit 1 — asserted means held in reset */
#define REFLEX_PCR_RMT_RST_EN 0x00000002u
/* PCR.RMT_SCLK_CONF.SCLK_EN bit 22 */
#define REFLEX_PCR_RMT_SCLK_EN 0x00400000u
/* SPI0.SPI_MEM_MMU_POWER_CTRL.SPI_MMU_PAGE_SIZE width 2 — field value mask */
#define REFLEX_SPI_MEM_MMU_PAGE_SIZE 0x00000003u
/* LP_WDT.WDTCONFIG0.WDT_STG0 width 3 — 3 bits: 0 off, 3 reset system, 4 reset RTC too */
#define REFLEX_LP_WDT_STG_MASK 0x00000007u
/* LP_WDT.WDTCONFIG0.WDT_SYS_RESET_LENGTH width 3 — same width as the CPU field */
#define REFLEX_LP_WDT_RESET_LEN_MASK 0x00000007u
/* LEDC.CH%s_CONF0.TIMER_SEL width 2 */
#define REFLEX_LEDC_TIMER_SEL_MASK 0x00000003u
/* LEDC.CH%s_DUTY.DUTY width 25 */
#define REFLEX_LEDC_DUTY_MASK 0x01FFFFFFu
/* LEDC.TIMER%s_CONF.DUTY_RES width 5 */
#define REFLEX_LEDC_DUTY_RES_MASK 0x0000001Fu
/* LEDC.TIMER%s_CONF.CLK_DIV width 18 — Q10.8 divider */
#define REFLEX_LEDC_CLK_DIV_MASK 0x0003FFFFu
/* IEEE802154.COEX_PTI.COEX_PTI width 4 — traffic priority, 4 bits */
#define REFLEX_154_COEX_PTI_MASK 0x0000000Fu
/* IEEE802154.COEX_PTI.COEX_ACK_PTI width 4 — hardware-ACK priority, 4 bits */
#define REFLEX_154_COEX_ACK_PTI_MASK 0x0000000Fu
/* IEEE802154.CHANNEL.HOP width 7 — frequency index field */
#define REFLEX_154_CHANNEL_HOP_MASK 0x0000007Fu
/* IEEE802154.TX_POWER.TX_POWER width 5 */
#define REFLEX_154_TX_POWER_MASK 0x0000001Fu
/* IEEE802154.ED_SCAN_CFG.ED_SAMPLE_MODE width 2 */
#define REFLEX_154_ED_SAMPLE_MODE_MASK 0x00000003u
/* IEEE802154.RX_STATUS.RX_STATE width 3 */
#define REFLEX_154_RX_STATE_MASK 0x00000007u
/* MODEM_SYSCON.CLK_CONF_POWER_ST.CLK_ZB_ST_MAP width 4 — 4 bits; every ICG field has the same width
 */
#define REFLEX_MODEM_ICG_MASK 0x0000000Fu
/* PCR.LEDC_SCLK_CONF.LEDC_SCLK_SEL width 2 — 3 selects XTAL */
#define REFLEX_PCR_LEDC_SCLK_SEL_MASK 0x00000003u
/* PCNT.U%s_CONF0.CH0_POS_MODE width 2 — all four mode fields are 2 bits */
#define REFLEX_PCNT_MODE_MASK 0x00000003u
/* PCNT.U%s_CONF2.CNT_H_LIM width 16 */
#define REFLEX_PCNT_LIM_MASK 0x0000FFFFu
/* PCNT.U%s_CNT.CNT width 16 — 16-bit, read as signed */
#define REFLEX_PCNT_CNT_MASK 0x0000FFFFu
/* RMT.CH%s_TX_CONF0.DIV_CNT width 8 — channel clock divider */
#define REFLEX_RMT_DIV_CNT_MASK 0x000000FFu
/* RMT.CH%s_TX_CONF0.MEM_SIZE width 3 — in 48-word blocks */
#define REFLEX_RMT_MEM_SIZE_MASK 0x00000007u
/* RMT.SYS_CONF.SCLK_DIV_NUM width 8 */
#define REFLEX_RMT_SCLK_DIV_NUM_MASK 0x000000FFu
/* RMT.SYS_CONF.SCLK_SEL width 2 */
#define REFLEX_RMT_SCLK_SEL_MASK 0x00000003u
/* RMT.CH%s_TX_LIM.TX_LIM width 9 */
#define REFLEX_RMT_TX_LIM_MASK 0x000001FFu
/* PCR.RMT_SCLK_CONF.SCLK_DIV_A width 6 */
#define REFLEX_PCR_RMT_SCLK_DIV_A_MASK 0x0000003Fu
/* PCR.RMT_SCLK_CONF.SCLK_DIV_B width 6 */
#define REFLEX_PCR_RMT_SCLK_DIV_B_MASK 0x0000003Fu
/* PCR.RMT_SCLK_CONF.SCLK_DIV_NUM width 8 */
#define REFLEX_PCR_RMT_SCLK_DIV_NUM_MASK 0x000000FFu
/* PCR.RMT_SCLK_CONF.SCLK_SEL width 2 */
#define REFLEX_PCR_RMT_SCLK_SEL_MASK 0x00000003u
/* SPI0.SPI_MEM_MMU_POWER_CTRL.SPI_MMU_PAGE_SIZE bit 3 — field shift */
#define REFLEX_SPI_MEM_MMU_PAGE_SIZE_S 0x00000003u
/* LP_WDT.WDTCONFIG0.WDT_STG0 bit 28 */
#define REFLEX_LP_WDT_STG0_S 0x0000001Cu
/* LP_WDT.WDTCONFIG0.WDT_SYS_RESET_LENGTH bit 13 */
#define REFLEX_LP_WDT_SYS_RESET_LEN_S 0x0000000Du
/* LP_WDT.WDTCONFIG0.WDT_CPU_RESET_LENGTH bit 16 */
#define REFLEX_LP_WDT_CPU_RESET_LEN_S 0x00000010u
/* LEDC.CH%s_CONF0.TIMER_SEL bit 0 */
#define REFLEX_LEDC_TIMER_SEL_S 0x00000000u
/* LEDC.CH%s_DUTY.DUTY bit 0 */
#define REFLEX_LEDC_DUTY_S 0x00000000u
/* IEEE802154.COEX_PTI.COEX_PTI bit 0 */
#define REFLEX_154_COEX_PTI_S 0x00000000u
/* IEEE802154.COEX_PTI.COEX_ACK_PTI bit 4 */
#define REFLEX_154_COEX_ACK_PTI_S 0x00000004u
/* IEEE802154.CHANNEL.HOP bit 0 */
#define REFLEX_154_CHANNEL_HOP_S 0x00000000u
/* IEEE802154.TX_POWER.TX_POWER bit 0 */
#define REFLEX_154_TX_POWER_S 0x00000000u
/* IEEE802154.ED_SCAN_CFG.ED_SAMPLE_MODE bit 11 */
#define REFLEX_154_ED_SAMPLE_MODE_S 0x0000000Bu
/* IEEE802154.RX_STATUS.RX_STATE bit 16 */
#define REFLEX_154_RX_STATE_S 0x00000010u
/* MODEM_SYSCON.CLK_CONF_POWER_ST.CLK_ZB_ST_MAP bit 8 */
#define REFLEX_MODEM_ICG_ZB_S 0x00000008u
/* MODEM_SYSCON.CLK_CONF_POWER_ST.CLK_FE_ST_MAP bit 12 */
#define REFLEX_MODEM_ICG_FE_S 0x0000000Cu
/* MODEM_SYSCON.CLK_CONF_POWER_ST.CLK_BT_ST_MAP bit 16 */
#define REFLEX_MODEM_ICG_BT_S 0x00000010u
/* MODEM_SYSCON.CLK_CONF_POWER_ST.CLK_WIFI_ST_MAP bit 20 */
#define REFLEX_MODEM_ICG_WIFI_S 0x00000014u
/* MODEM_SYSCON.CLK_CONF_POWER_ST.CLK_MODEM_PERI_ST_MAP bit 24 */
#define REFLEX_MODEM_ICG_PERI_S 0x00000018u
/* MODEM_SYSCON.CLK_CONF_POWER_ST.CLK_MODEM_APB_ST_MAP bit 28 */
#define REFLEX_MODEM_ICG_APB_S 0x0000001Cu
/* MODEM_LPCON.CLK_CONF_POWER_ST.CLK_WIFIPWR_ST_MAP bit 16 */
#define REFLEX_MODEM_ICG_WIFIPWR_S 0x00000010u
/* MODEM_LPCON.CLK_CONF_POWER_ST.CLK_COEX_ST_MAP bit 20 */
#define REFLEX_MODEM_ICG_COEX_S 0x00000014u
/* MODEM_LPCON.CLK_CONF_POWER_ST.CLK_I2C_MST_ST_MAP bit 24 */
#define REFLEX_MODEM_ICG_I2C_MST_S 0x00000018u
/* MODEM_LPCON.CLK_CONF_POWER_ST.CLK_LP_APB_ST_MAP bit 28 */
#define REFLEX_MODEM_ICG_LP_APB_S 0x0000001Cu
/* LEDC.TIMER%s_CONF.DUTY_RES bit 0 */
#define REFLEX_LEDC_DUTY_RES_S 0x00000000u
/* LEDC.TIMER%s_CONF.CLK_DIV bit 5 */
#define REFLEX_LEDC_CLK_DIV_S 0x00000005u
/* PCR.LEDC_SCLK_CONF.LEDC_SCLK_SEL bit 20 */
#define REFLEX_PCR_LEDC_SCLK_SEL_S 0x00000014u
/* PCNT.U%s_CONF0.CH0_POS_MODE bit 18 */
#define REFLEX_PCNT_CH0_POS_MODE_S 0x00000012u
/* PCNT.U%s_CONF0.CH0_NEG_MODE bit 16 */
#define REFLEX_PCNT_CH0_NEG_MODE_S 0x00000010u
/* PCNT.U%s_CONF0.CH0_HCTRL_MODE bit 20 */
#define REFLEX_PCNT_CH0_HCTRL_MODE_S 0x00000014u
/* PCNT.U%s_CONF0.CH0_LCTRL_MODE bit 22 */
#define REFLEX_PCNT_CH0_LCTRL_MODE_S 0x00000016u
/* PCNT.U%s_CONF2.CNT_H_LIM bit 0 */
#define REFLEX_PCNT_CNT_H_LIM_S 0x00000000u
/* PCNT.U%s_CONF2.CNT_L_LIM bit 16 */
#define REFLEX_PCNT_CNT_L_LIM_S 0x00000010u
/* RMT.CH%s_TX_CONF0.DIV_CNT bit 8 */
#define REFLEX_RMT_DIV_CNT_S 0x00000008u
/* RMT.CH%s_TX_CONF0.MEM_SIZE bit 16 */
#define REFLEX_RMT_MEM_SIZE_S 0x00000010u
/* RMT.SYS_CONF.SCLK_DIV_NUM bit 4 */
#define REFLEX_RMT_SCLK_DIV_NUM_S 0x00000004u
/* RMT.SYS_CONF.SCLK_SEL bit 24 */
#define REFLEX_RMT_SCLK_SEL_S 0x00000018u
/* RMT.CH%s_TX_LIM.TX_LIM bit 0 */
#define REFLEX_RMT_TX_LIM_S 0x00000000u
/* PCR.RMT_SCLK_CONF.SCLK_DIV_A bit 0 */
#define REFLEX_PCR_RMT_SCLK_DIV_A_S 0x00000000u
/* PCR.RMT_SCLK_CONF.SCLK_DIV_B bit 6 */
#define REFLEX_PCR_RMT_SCLK_DIV_B_S 0x00000006u
/* PCR.RMT_SCLK_CONF.SCLK_DIV_NUM bit 12 */
#define REFLEX_PCR_RMT_SCLK_DIV_NUM_S 0x0000000Cu
/* PCR.RMT_SCLK_CONF.SCLK_SEL bit 20 */
#define REFLEX_PCR_RMT_SCLK_SEL_S 0x00000014u
/* literal — CPU memory map, not a peripheral: HP SRAM instruction bus window */
#define REFLEX_SOC_IRAM_LOW 0x40800000u
/* literal — CPU memory map */
#define REFLEX_SOC_IRAM_HIGH 0x40880000u
/* literal — CPU memory map: LP SRAM */
#define REFLEX_SOC_RTC_IRAM_LOW 0x50000000u
/* literal — CPU memory map: LP SRAM */
#define REFLEX_SOC_RTC_IRAM_HIGH 0x50004000u
/* literal — watchdog write-protect magic; a key, not an address */
#define REFLEX_TIMG_WDT_WKEY_VALUE 0x50D83AA1u
/* literal — GPIO matrix signal index; lives in gpio_sig_map, not the SVD */
#define REFLEX_LEDC_LS_SIG_OUT0_IDX 0x00000000u
/* literal — GPIO matrix signal index; gpio_sig_map, not the SVD. Unit 0 channel 0 edge input */
#define REFLEX_PCNT_SIG_CH0_IN0_IDX 0x00000065u
/* literal — GPIO matrix signal index; the level/control input gating the same channel */
#define REFLEX_PCNT_CTRL_CH0_IN0_IDX 0x00000067u
/* literal — gpio_pins.h, not the SVD. Routing this into a signal index is how the matrix
 * disconnects an input */
#define REFLEX_GPIO_MATRIX_CONST_ZERO_INPUT 0x0000003Cu
/* literal — hal/mwdt_ll.h, not the SVD. Unlocks a timer-group watchdog */
#define REFLEX_TIMG_WDT_WKEY 0x50D83AA1u
/* literal — hal/lpwdt_ll.h, not the SVD. Unlocks the watchdog registers */
#define REFLEX_LP_WDT_WKEY 0x50D83AA1u
/* literal — hal enum, not the SVD */
#define REFLEX_154_CMD_TX_START 0x00000041u
/* literal — hal enum, not the SVD */
#define REFLEX_154_CMD_RX_START 0x00000042u
/* literal — hal enum, not the SVD */
#define REFLEX_154_CMD_STOP 0x00000045u
/* literal — EVENT_STATUS bit 0 */
#define REFLEX_154_EVENT_TX_DONE 0x00000001u
/* literal — EVENT_STATUS bit 1 */
#define REFLEX_154_EVENT_RX_DONE 0x00000002u
/* literal — EVENT_STATUS bit 5 */
#define REFLEX_154_EVENT_TX_ABORT 0x00000020u
/* literal — GPIO matrix signal index; gpio_sig_map, not the SVD. Routing this back onto a pin is
 * how a peripheral output is detached, and it was a bare 128 in shell.c */
#define REFLEX_SIG_GPIO_OUT_IDX 0x00000080u
/* literal — GPIO matrix signal index; gpio_sig_map, not the SVD. Guessed as 51 first and the bridge
 * rejected it, which is the entire point of the bridge */
#define REFLEX_RMT_SIG_OUT0_IDX 0x00000047u
/* literal — IO_MUX function-select field mask (3 bits) */
#define REFLEX_IO_MUX_MCU_SEL_V 0x00000007u
/* literal — capability flag from soc_caps.h */
#define REFLEX_SOC_SYSTIMER_FIXED_DIVIDER 0x00000001u
/* literal — interrupt-matrix source number; an enum position in soc/interrupts.h, not SVD data */
#define REFLEX_INTR_SRC_SYSTIMER_TARGET1 0x0000003Au
/* literal — interrupt-matrix source number; enum position in soc/interrupts.h. Needed to own
 * console RX: the ESP-IDF driver cannot be left installed alongside direct FIFO reads, and polling
 * cannot replace it because the shell idles 50ms while a 64-byte FIFO fills in 5.5ms at 115200 baud
 */
#define REFLEX_INTR_SRC_USB_SERIAL_JTAG 0x00000030u
/* literal — interrupt-matrix source number; enum position in soc/interrupts.h. The 802.15.4 MAC.
 * Needed so the hand-off can adopt the radio's line rather than quiescing it: under Reflex's trap
 * vector only the tick and console were live, which left the blob-free radio unable to receive */
#define REFLEX_INTR_SRC_ZB_MAC 0x0000000Cu

#endif /* REFLEX_SOC_ESP32C6_H */
