/* Generated by tools/soc_scraper.py from tools/esp32c6.svd — do not edit.
 *
 * Reflex's own ESP32-C6 register constants, replacing the ESP-IDF
 * soc register headers. These are silicon facts rather than ESP-IDF code:
 * every address and bit position below is computed from the vendor SVD that
 * already backs the 12,738-node shadow atlas, so nothing here was copied by
 * hand from a vendor header where a typo would write to a real register.
 *
 * Equivalence with the ESP-IDF macros these replace is proved, not asserted:
 * `make soc-bridge` compiles a translation unit of _Static_asserts inside a
 * real ESP-IDF build. Regenerate with `make soc-header`.
 */
#ifndef REFLEX_SOC_ESP32C6_H
#define REFLEX_SOC_ESP32C6_H

#include <stdint.h>

/* LP_WDT.SWD_CONF @ base+0x1C — super-watchdog config */
#define REFLEX_LP_WDT_SWD_CONFIG_REG 0x600B1C1Cu
/* LP_WDT.SWD_WPROTECT @ base+0x20 — super-watchdog write protect */
#define REFLEX_LP_WDT_SWD_WPROTECT_REG 0x600B1C20u
/* LP_WDT.SWD_CONF.SWD_AUTO_FEED_EN bit 18 */
#define REFLEX_LP_WDT_SWD_AUTO_FEED_EN 0x00040000u
/* LP_WDT.INT_ENA_RTC @ base+0x2C — IDF drops the _RTC suffix */
#define REFLEX_LP_WDT_INT_ENA_REG 0x600B1C2Cu
/* LP_WDT.INT_CLR_RTC @ base+0x30 — IDF drops the _RTC suffix */
#define REFLEX_LP_WDT_INT_CLR_REG 0x600B1C30u
/* LP_WDT.INT_ENA_RTC.WDT_INT_ENA bit 31 */
#define REFLEX_LP_WDT_LP_WDT_INT_ENA 0x80000000u
/* LP_WDT.INT_CLR_RTC.WDT_INT_CLR bit 31 */
#define REFLEX_LP_WDT_LP_WDT_INT_CLR 0x80000000u
/* LP_WDT.INT_ENA_RTC.SUPER_WDT_INT_ENA bit 30 */
#define REFLEX_LP_WDT_SUPER_WDT_INT_ENA 0x40000000u
/* LP_WDT.INT_CLR_RTC.SUPER_WDT_INT_CLR bit 30 */
#define REFLEX_LP_WDT_SUPER_WDT_INT_CLR 0x40000000u
/* TIMG0.WDTFEED @ base+0x60 — IDF indexes by group; Boot0 only uses group 0 */
#define REFLEX_TIMG0_WDTFEED_REG 0x60008060u
/* TIMG0.WDTWPROTECT @ base+0x64 */
#define REFLEX_TIMG0_WDTWPROTECT_REG 0x60008064u
/* LP_AON.STORE0 @ base+0x0 — scratch, survives deep sleep */
#define REFLEX_LP_AON_STORE0_REG 0x600B1000u
/* LP_AON.SYS_CFG @ base+0x34 */
#define REFLEX_LP_AON_SYS_CFG_REG 0x600B1034u
/* LP_AON.SYS_CFG.HPSYS_SW_RESET bit 31 */
#define REFLEX_LP_AON_HPSYS_SW_RESET 0x80000000u
/* LP_ANA.LP_INT_ENA @ base+0x28 — SVD peripheral is LP_ANA */
#define REFLEX_LP_ANA_INT_ENA_REG 0x600B2C28u
/* LP_ANA.LP_INT_CLR @ base+0x2C */
#define REFLEX_LP_ANA_INT_CLR_REG 0x600B2C2Cu
/* LP_ANA.LP_INT_ENA.BOD_MODE0_LP_INT_ENA bit 31 */
#define REFLEX_LP_ANA_BOD_MODE0_INT_ENA 0x80000000u
/* LP_ANA.LP_INT_CLR.BOD_MODE0_LP_INT_CLR bit 31 */
#define REFLEX_LP_ANA_BOD_MODE0_INT_CLR 0x80000000u
/* PMU.HP_INT_ENA @ base+0x164 */
#define REFLEX_PMU_HP_INT_ENA_REG 0x600B0164u
/* PMU.HP_INT_ENA.SOC_WAKEUP_INT_ENA bit 31 */
#define REFLEX_PMU_SOC_WAKEUP_INT_ENA 0x80000000u
/* PMU.HP_INT_ENA.SOC_SLEEP_REJECT_INT_ENA bit 30 */
#define REFLEX_PMU_SOC_SLEEP_REJECT_INT_ENA 0x40000000u
/* ASSIST_DEBUG.CORE_0_RCD_EN @ base+0x44 */
#define REFLEX_ASSIST_DEBUG_CORE_0_RCD_EN_REG 0x600C2044u
/* ASSIST_DEBUG.CORE_0_RCD_EN.CORE_0_RCD_RECORDEN bit 0 */
#define REFLEX_ASSIST_DEBUG_CORE_0_RCD_RECORDEN 0x00000001u
/* ASSIST_DEBUG.CORE_0_RCD_EN.CORE_0_RCD_PDEBUGEN bit 1 */
#define REFLEX_ASSIST_DEBUG_CORE_0_RCD_PDEBUGEN 0x00000002u
/* PCR.ASSIST_CONF @ base+0x100 */
#define REFLEX_PCR_ASSIST_CONF_REG 0x60096100u
/* PCR.ASSIST_CONF.ASSIST_CLK_EN bit 0 */
#define REFLEX_PCR_ASSIST_CLK_EN 0x00000001u
/* PCR.ASSIST_CONF.ASSIST_RST_EN bit 1 */
#define REFLEX_PCR_ASSIST_RST_EN 0x00000002u
/* EXTMEM.L1_CACHE_CTRL @ base+0x4 */
#define REFLEX_EXTMEM_L1_CACHE_CTRL_REG 0x600C8004u
/* EXTMEM.L1_CACHE_CTRL.L1_CACHE_SHUT_BUS0 bit 0 — IDF calls bus0 the IBUS */
#define REFLEX_EXTMEM_L1_CACHE_SHUT_IBUS 0x00000001u
/* EXTMEM.L1_CACHE_CTRL.L1_CACHE_SHUT_BUS1 bit 1 — IDF calls bus1 the DBUS */
#define REFLEX_EXTMEM_L1_CACHE_SHUT_DBUS 0x00000002u
/* SPI0.SPI_MEM_MMU_ITEM_CONTENT @ base+0x37C — IDF indexes by SPI unit; Boot0 uses 0 */
#define REFLEX_SPI_MEM_MMU_ITEM_CONTENT_REG 0x6000237Cu
/* SPI0.SPI_MEM_MMU_ITEM_INDEX @ base+0x380 */
#define REFLEX_SPI_MEM_MMU_ITEM_INDEX_REG 0x60002380u
/* SPI0.SPI_MEM_MMU_POWER_CTRL @ base+0x384 */
#define REFLEX_SPI_MEM_MMU_POWER_CTRL_REG 0x60002384u
/* SYSTIMER base — peripheral base, not a register */
#define REFLEX_DR_REG_SYSTIMER_BASE 0x6000A000u
/* SPI0.SPI_MEM_MMU_POWER_CTRL.SPI_MMU_PAGE_SIZE width 2 — field value mask */
#define REFLEX_SPI_MEM_MMU_PAGE_SIZE 0x00000003u
/* SPI0.SPI_MEM_MMU_POWER_CTRL.SPI_MMU_PAGE_SIZE bit 3 — field shift */
#define REFLEX_SPI_MEM_MMU_PAGE_SIZE_S 0x00000003u
/* literal — CPU memory map, not a peripheral: HP SRAM instruction bus window */
#define REFLEX_SOC_IRAM_LOW 0x40800000u
/* literal — CPU memory map */
#define REFLEX_SOC_IRAM_HIGH 0x40880000u
/* literal — CPU memory map: LP SRAM */
#define REFLEX_SOC_RTC_IRAM_LOW 0x50000000u
/* literal — CPU memory map: LP SRAM */
#define REFLEX_SOC_RTC_IRAM_HIGH 0x50004000u
/* literal — watchdog write-protect magic; a key, not an address */
#define REFLEX_TIMG_WDT_WKEY_VALUE 0x50D83AA1u
/* literal — GPIO matrix signal index; lives in gpio_sig_map, not the SVD */
#define REFLEX_LEDC_LS_SIG_OUT0_IDX 0x00000000u
/* literal — IO_MUX function-select field mask (3 bits) */
#define REFLEX_IO_MUX_MCU_SEL_V 0x00000007u
/* literal — capability flag from soc_caps.h */
#define REFLEX_SOC_SYSTIMER_FIXED_DIVIDER 0x00000001u

#endif /* REFLEX_SOC_ESP32C6_H */
