/* Generated by tools/soc_scraper.py --emit-bridge — do not edit.
 *
 * Proof, not paperwork. Every constant in reflex_soc_esp32c6.h is derived
 * from the vendor SVD; this compiles those values against the ESP-IDF macros
 * they replace and fails the build on any divergence. It exists so the
 * cutover away from the ESP-IDF soc headers is verified, not believed.
 *
 * Built by `make soc-bridge`, which compiles it inside the ESP-IDF container.
 * It is deliberately not part of the firmware: it is a test that happens to
 * be a translation unit, and it is the only file left that includes both.
 */
#include "reflex_soc_esp32c6.h"

#include "soc/soc.h"
#include "soc/soc_caps.h"
#include "soc/reg_base.h"
#include "soc/systimer_reg.h"
#include "soc/gpio_sig_map.h"
#include "soc/io_mux_reg.h"
#include "soc/lp_wdt_reg.h"
#include "soc/lp_aon_reg.h"
#include "soc/lp_analog_peri_reg.h"
#include "soc/pmu_reg.h"
#include "soc/pcr_reg.h"
#include "soc/extmem_reg.h"
#include "soc/assist_debug_reg.h"
#include "soc/spi_mem_reg.h"
#include "soc/timer_group_reg.h"
#include "soc/wdt_periph.h"

_Static_assert(REFLEX_LP_WDT_SWD_CONFIG_REG == (uint32_t)(LP_WDT_SWD_CONFIG_REG),
               "REFLEX_LP_WDT_SWD_CONFIG_REG diverges from LP_WDT_SWD_CONFIG_REG");
_Static_assert(REFLEX_LP_WDT_SWD_WPROTECT_REG == (uint32_t)(LP_WDT_SWD_WPROTECT_REG),
               "REFLEX_LP_WDT_SWD_WPROTECT_REG diverges from LP_WDT_SWD_WPROTECT_REG");
_Static_assert(REFLEX_LP_WDT_SWD_AUTO_FEED_EN == (uint32_t)(LP_WDT_SWD_AUTO_FEED_EN),
               "REFLEX_LP_WDT_SWD_AUTO_FEED_EN diverges from LP_WDT_SWD_AUTO_FEED_EN");
_Static_assert(REFLEX_LP_WDT_INT_ENA_REG == (uint32_t)(LP_WDT_INT_ENA_REG),
               "REFLEX_LP_WDT_INT_ENA_REG diverges from LP_WDT_INT_ENA_REG");
_Static_assert(REFLEX_LP_WDT_INT_CLR_REG == (uint32_t)(LP_WDT_INT_CLR_REG),
               "REFLEX_LP_WDT_INT_CLR_REG diverges from LP_WDT_INT_CLR_REG");
_Static_assert(REFLEX_LP_WDT_LP_WDT_INT_ENA == (uint32_t)(LP_WDT_LP_WDT_INT_ENA),
               "REFLEX_LP_WDT_LP_WDT_INT_ENA diverges from LP_WDT_LP_WDT_INT_ENA");
_Static_assert(REFLEX_LP_WDT_LP_WDT_INT_CLR == (uint32_t)(LP_WDT_LP_WDT_INT_CLR),
               "REFLEX_LP_WDT_LP_WDT_INT_CLR diverges from LP_WDT_LP_WDT_INT_CLR");
_Static_assert(REFLEX_LP_WDT_SUPER_WDT_INT_ENA == (uint32_t)(LP_WDT_SUPER_WDT_INT_ENA),
               "REFLEX_LP_WDT_SUPER_WDT_INT_ENA diverges from LP_WDT_SUPER_WDT_INT_ENA");
_Static_assert(REFLEX_LP_WDT_SUPER_WDT_INT_CLR == (uint32_t)(LP_WDT_SUPER_WDT_INT_CLR),
               "REFLEX_LP_WDT_SUPER_WDT_INT_CLR diverges from LP_WDT_SUPER_WDT_INT_CLR");
_Static_assert(REFLEX_TIMG0_WDTFEED_REG == (uint32_t)(TIMG_WDTFEED_REG(0)),
               "REFLEX_TIMG0_WDTFEED_REG diverges from TIMG_WDTFEED_REG(0)");
_Static_assert(REFLEX_TIMG0_WDTWPROTECT_REG == (uint32_t)(TIMG_WDTWPROTECT_REG(0)),
               "REFLEX_TIMG0_WDTWPROTECT_REG diverges from TIMG_WDTWPROTECT_REG(0)");
_Static_assert(REFLEX_LP_AON_STORE0_REG == (uint32_t)(LP_AON_STORE0_REG),
               "REFLEX_LP_AON_STORE0_REG diverges from LP_AON_STORE0_REG");
_Static_assert(REFLEX_LP_AON_SYS_CFG_REG == (uint32_t)(LP_AON_SYS_CFG_REG),
               "REFLEX_LP_AON_SYS_CFG_REG diverges from LP_AON_SYS_CFG_REG");
_Static_assert(REFLEX_LP_AON_HPSYS_SW_RESET == (uint32_t)(LP_AON_HPSYS_SW_RESET),
               "REFLEX_LP_AON_HPSYS_SW_RESET diverges from LP_AON_HPSYS_SW_RESET");
_Static_assert(REFLEX_LP_ANA_INT_ENA_REG == (uint32_t)(LP_ANALOG_PERI_LP_ANA_LP_INT_ENA_REG),
               "REFLEX_LP_ANA_INT_ENA_REG diverges from LP_ANALOG_PERI_LP_ANA_LP_INT_ENA_REG");
_Static_assert(REFLEX_LP_ANA_INT_CLR_REG == (uint32_t)(LP_ANALOG_PERI_LP_ANA_LP_INT_CLR_REG),
               "REFLEX_LP_ANA_INT_CLR_REG diverges from LP_ANALOG_PERI_LP_ANA_LP_INT_CLR_REG");
_Static_assert(
    REFLEX_LP_ANA_BOD_MODE0_INT_ENA == (uint32_t)(LP_ANALOG_PERI_LP_ANA_BOD_MODE0_LP_INT_ENA),
    "REFLEX_LP_ANA_BOD_MODE0_INT_ENA diverges from LP_ANALOG_PERI_LP_ANA_BOD_MODE0_LP_INT_ENA");
_Static_assert(
    REFLEX_LP_ANA_BOD_MODE0_INT_CLR == (uint32_t)(LP_ANALOG_PERI_LP_ANA_BOD_MODE0_LP_INT_CLR),
    "REFLEX_LP_ANA_BOD_MODE0_INT_CLR diverges from LP_ANALOG_PERI_LP_ANA_BOD_MODE0_LP_INT_CLR");
_Static_assert(REFLEX_PMU_HP_INT_ENA_REG == (uint32_t)(PMU_HP_INT_ENA_REG),
               "REFLEX_PMU_HP_INT_ENA_REG diverges from PMU_HP_INT_ENA_REG");
_Static_assert(REFLEX_PMU_SOC_WAKEUP_INT_ENA == (uint32_t)(PMU_SOC_WAKEUP_INT_ENA),
               "REFLEX_PMU_SOC_WAKEUP_INT_ENA diverges from PMU_SOC_WAKEUP_INT_ENA");
_Static_assert(REFLEX_PMU_SOC_SLEEP_REJECT_INT_ENA == (uint32_t)(PMU_SOC_SLEEP_REJECT_INT_ENA),
               "REFLEX_PMU_SOC_SLEEP_REJECT_INT_ENA diverges from PMU_SOC_SLEEP_REJECT_INT_ENA");
_Static_assert(
    REFLEX_ASSIST_DEBUG_CORE_0_RCD_EN_REG == (uint32_t)(ASSIST_DEBUG_CORE_0_RCD_EN_REG),
    "REFLEX_ASSIST_DEBUG_CORE_0_RCD_EN_REG diverges from ASSIST_DEBUG_CORE_0_RCD_EN_REG");
_Static_assert(
    REFLEX_ASSIST_DEBUG_CORE_0_RCD_RECORDEN == (uint32_t)(ASSIST_DEBUG_CORE_0_RCD_RECORDEN),
    "REFLEX_ASSIST_DEBUG_CORE_0_RCD_RECORDEN diverges from ASSIST_DEBUG_CORE_0_RCD_RECORDEN");
_Static_assert(
    REFLEX_ASSIST_DEBUG_CORE_0_RCD_PDEBUGEN == (uint32_t)(ASSIST_DEBUG_CORE_0_RCD_PDEBUGEN),
    "REFLEX_ASSIST_DEBUG_CORE_0_RCD_PDEBUGEN diverges from ASSIST_DEBUG_CORE_0_RCD_PDEBUGEN");
_Static_assert(REFLEX_PCR_ASSIST_CONF_REG == (uint32_t)(PCR_ASSIST_CONF_REG),
               "REFLEX_PCR_ASSIST_CONF_REG diverges from PCR_ASSIST_CONF_REG");
_Static_assert(REFLEX_PCR_ASSIST_CLK_EN == (uint32_t)(PCR_ASSIST_CLK_EN),
               "REFLEX_PCR_ASSIST_CLK_EN diverges from PCR_ASSIST_CLK_EN");
_Static_assert(REFLEX_PCR_ASSIST_RST_EN == (uint32_t)(PCR_ASSIST_RST_EN),
               "REFLEX_PCR_ASSIST_RST_EN diverges from PCR_ASSIST_RST_EN");
_Static_assert(REFLEX_EXTMEM_L1_CACHE_CTRL_REG == (uint32_t)(EXTMEM_L1_CACHE_CTRL_REG),
               "REFLEX_EXTMEM_L1_CACHE_CTRL_REG diverges from EXTMEM_L1_CACHE_CTRL_REG");
_Static_assert(REFLEX_EXTMEM_L1_CACHE_SHUT_IBUS == (uint32_t)(EXTMEM_L1_CACHE_SHUT_IBUS),
               "REFLEX_EXTMEM_L1_CACHE_SHUT_IBUS diverges from EXTMEM_L1_CACHE_SHUT_IBUS");
_Static_assert(REFLEX_EXTMEM_L1_CACHE_SHUT_DBUS == (uint32_t)(EXTMEM_L1_CACHE_SHUT_DBUS),
               "REFLEX_EXTMEM_L1_CACHE_SHUT_DBUS diverges from EXTMEM_L1_CACHE_SHUT_DBUS");
_Static_assert(REFLEX_SPI_MEM_MMU_ITEM_CONTENT_REG == (uint32_t)(SPI_MEM_MMU_ITEM_CONTENT_REG(0)),
               "REFLEX_SPI_MEM_MMU_ITEM_CONTENT_REG diverges from SPI_MEM_MMU_ITEM_CONTENT_REG(0)");
_Static_assert(REFLEX_SPI_MEM_MMU_ITEM_INDEX_REG == (uint32_t)(SPI_MEM_MMU_ITEM_INDEX_REG(0)),
               "REFLEX_SPI_MEM_MMU_ITEM_INDEX_REG diverges from SPI_MEM_MMU_ITEM_INDEX_REG(0)");
_Static_assert(REFLEX_SPI_MEM_MMU_POWER_CTRL_REG == (uint32_t)(SPI_MEM_MMU_POWER_CTRL_REG(0)),
               "REFLEX_SPI_MEM_MMU_POWER_CTRL_REG diverges from SPI_MEM_MMU_POWER_CTRL_REG(0)");
_Static_assert(REFLEX_DR_REG_SYSTIMER_BASE == (uint32_t)(DR_REG_SYSTIMER_BASE),
               "REFLEX_DR_REG_SYSTIMER_BASE diverges from DR_REG_SYSTIMER_BASE");
_Static_assert(REFLEX_SPI_MEM_MMU_PAGE_SIZE == (uint32_t)(SPI_MEM_MMU_PAGE_SIZE),
               "REFLEX_SPI_MEM_MMU_PAGE_SIZE diverges from SPI_MEM_MMU_PAGE_SIZE");
_Static_assert(REFLEX_SPI_MEM_MMU_PAGE_SIZE_S == (uint32_t)(SPI_MEM_MMU_PAGE_SIZE_S),
               "REFLEX_SPI_MEM_MMU_PAGE_SIZE_S diverges from SPI_MEM_MMU_PAGE_SIZE_S");
_Static_assert(REFLEX_SOC_IRAM_LOW == (uint32_t)(SOC_IRAM_LOW),
               "REFLEX_SOC_IRAM_LOW diverges from SOC_IRAM_LOW");
_Static_assert(REFLEX_SOC_IRAM_HIGH == (uint32_t)(SOC_IRAM_HIGH),
               "REFLEX_SOC_IRAM_HIGH diverges from SOC_IRAM_HIGH");
_Static_assert(REFLEX_SOC_RTC_IRAM_LOW == (uint32_t)(SOC_RTC_IRAM_LOW),
               "REFLEX_SOC_RTC_IRAM_LOW diverges from SOC_RTC_IRAM_LOW");
_Static_assert(REFLEX_SOC_RTC_IRAM_HIGH == (uint32_t)(SOC_RTC_IRAM_HIGH),
               "REFLEX_SOC_RTC_IRAM_HIGH diverges from SOC_RTC_IRAM_HIGH");
_Static_assert(REFLEX_TIMG_WDT_WKEY_VALUE == (uint32_t)(TIMG_WDT_WKEY_VALUE),
               "REFLEX_TIMG_WDT_WKEY_VALUE diverges from TIMG_WDT_WKEY_VALUE");
_Static_assert(REFLEX_LEDC_LS_SIG_OUT0_IDX == (uint32_t)(LEDC_LS_SIG_OUT0_IDX),
               "REFLEX_LEDC_LS_SIG_OUT0_IDX diverges from LEDC_LS_SIG_OUT0_IDX");
_Static_assert(REFLEX_IO_MUX_MCU_SEL_V == (uint32_t)(MCU_SEL),
               "REFLEX_IO_MUX_MCU_SEL_V diverges from MCU_SEL");
_Static_assert(REFLEX_SOC_SYSTIMER_FIXED_DIVIDER == (uint32_t)(SOC_SYSTIMER_FIXED_DIVIDER),
               "REFLEX_SOC_SYSTIMER_FIXED_DIVIDER diverges from SOC_SYSTIMER_FIXED_DIVIDER");

/* Silence the unused-translation-unit warning. */
const int reflex_soc_bridge_ok = 1;
