/* Generated by tools/soc_scraper.py --emit-bridge — do not edit.
 *
 * Proof, not paperwork. Every constant in reflex_soc_esp32c6.h is derived
 * from the vendor SVD; this compiles those values against the ESP-IDF macros
 * they replace and fails the build on any divergence. It exists so the
 * cutover away from the ESP-IDF soc headers is verified, not believed.
 *
 * Built by `make soc-bridge`, which compiles it inside the ESP-IDF container.
 * It is deliberately not part of the firmware: it is a test that happens to
 * be a translation unit, and it is the only file left that includes both.
 */
#include "reflex_soc_esp32c6.h"

#include "soc/soc.h"
#include "soc/soc_caps.h"
#include "soc/reg_base.h"
#include "soc/systimer_reg.h"
#include "soc/usb_serial_jtag_reg.h"
#include "soc/gpio_sig_map.h"
#include "soc/io_mux_reg.h"
#include "soc/lp_wdt_reg.h"
#include "hal/lpwdt_ll.h"
#include "soc/lp_aon_reg.h"
#include "soc/lp_analog_peri_reg.h"
#include "soc/pmu_reg.h"
#include "soc/pcr_reg.h"
#include "soc/ledc_reg.h"
#include "soc/pcnt_reg.h"
#include "soc/gpio_pins.h"
#include "soc/rmt_reg.h"
#include "soc/extmem_reg.h"
#include "soc/assist_debug_reg.h"
#include "soc/spi_mem_reg.h"
#include "soc/timer_group_reg.h"
#include "soc/wdt_periph.h"
#include "soc/interrupts.h"

_Static_assert(REFLEX_LP_WDT_CONFIG0_REG == (uint32_t)(LP_WDT_CONFIG0_REG),
               "REFLEX_LP_WDT_CONFIG0_REG diverges from LP_WDT_CONFIG0_REG");
_Static_assert(REFLEX_LP_WDT_CONFIG1_REG == (uint32_t)(LP_WDT_CONFIG1_REG),
               "REFLEX_LP_WDT_CONFIG1_REG diverges from LP_WDT_CONFIG1_REG");
_Static_assert(REFLEX_LP_WDT_FEED_REG == (uint32_t)(LP_WDT_FEED_REG),
               "REFLEX_LP_WDT_FEED_REG diverges from LP_WDT_FEED_REG");
_Static_assert(REFLEX_LP_WDT_WPROTECT_REG == (uint32_t)(LP_WDT_WPROTECT_REG),
               "REFLEX_LP_WDT_WPROTECT_REG diverges from LP_WDT_WPROTECT_REG");
_Static_assert(REFLEX_LP_WDT_EN == (uint32_t)(LP_WDT_WDT_EN),
               "REFLEX_LP_WDT_EN diverges from LP_WDT_WDT_EN");
_Static_assert(REFLEX_LP_WDT_PAUSE_IN_SLP == (uint32_t)(LP_WDT_WDT_PAUSE_IN_SLP),
               "REFLEX_LP_WDT_PAUSE_IN_SLP diverges from LP_WDT_WDT_PAUSE_IN_SLP");
_Static_assert(REFLEX_LP_WDT_PROCPU_RESET_EN == (uint32_t)(LP_WDT_WDT_PROCPU_RESET_EN),
               "REFLEX_LP_WDT_PROCPU_RESET_EN diverges from LP_WDT_WDT_PROCPU_RESET_EN");
_Static_assert(REFLEX_LP_WDT_CHIP_RESET_EN == (uint32_t)(LP_WDT_WDT_CHIP_RESET_EN),
               "REFLEX_LP_WDT_CHIP_RESET_EN diverges from LP_WDT_WDT_CHIP_RESET_EN");
_Static_assert(REFLEX_LP_WDT_SWD_CONFIG_REG == (uint32_t)(LP_WDT_SWD_CONFIG_REG),
               "REFLEX_LP_WDT_SWD_CONFIG_REG diverges from LP_WDT_SWD_CONFIG_REG");
_Static_assert(REFLEX_LP_WDT_SWD_WPROTECT_REG == (uint32_t)(LP_WDT_SWD_WPROTECT_REG),
               "REFLEX_LP_WDT_SWD_WPROTECT_REG diverges from LP_WDT_SWD_WPROTECT_REG");
_Static_assert(REFLEX_LP_WDT_SWD_AUTO_FEED_EN == (uint32_t)(LP_WDT_SWD_AUTO_FEED_EN),
               "REFLEX_LP_WDT_SWD_AUTO_FEED_EN diverges from LP_WDT_SWD_AUTO_FEED_EN");
_Static_assert(REFLEX_LP_WDT_INT_ENA_REG == (uint32_t)(LP_WDT_INT_ENA_REG),
               "REFLEX_LP_WDT_INT_ENA_REG diverges from LP_WDT_INT_ENA_REG");
_Static_assert(REFLEX_LP_WDT_INT_CLR_REG == (uint32_t)(LP_WDT_INT_CLR_REG),
               "REFLEX_LP_WDT_INT_CLR_REG diverges from LP_WDT_INT_CLR_REG");
_Static_assert(REFLEX_LP_WDT_LP_WDT_INT_ENA == (uint32_t)(LP_WDT_LP_WDT_INT_ENA),
               "REFLEX_LP_WDT_LP_WDT_INT_ENA diverges from LP_WDT_LP_WDT_INT_ENA");
_Static_assert(REFLEX_LP_WDT_LP_WDT_INT_CLR == (uint32_t)(LP_WDT_LP_WDT_INT_CLR),
               "REFLEX_LP_WDT_LP_WDT_INT_CLR diverges from LP_WDT_LP_WDT_INT_CLR");
_Static_assert(REFLEX_LP_WDT_SUPER_WDT_INT_ENA == (uint32_t)(LP_WDT_SUPER_WDT_INT_ENA),
               "REFLEX_LP_WDT_SUPER_WDT_INT_ENA diverges from LP_WDT_SUPER_WDT_INT_ENA");
_Static_assert(REFLEX_LP_WDT_SUPER_WDT_INT_CLR == (uint32_t)(LP_WDT_SUPER_WDT_INT_CLR),
               "REFLEX_LP_WDT_SUPER_WDT_INT_CLR diverges from LP_WDT_SUPER_WDT_INT_CLR");
_Static_assert(REFLEX_TIMG0_WDTFEED_REG == (uint32_t)(TIMG_WDTFEED_REG(0)),
               "REFLEX_TIMG0_WDTFEED_REG diverges from TIMG_WDTFEED_REG(0)");
_Static_assert(REFLEX_TIMG0_WDTWPROTECT_REG == (uint32_t)(TIMG_WDTWPROTECT_REG(0)),
               "REFLEX_TIMG0_WDTWPROTECT_REG diverges from TIMG_WDTWPROTECT_REG(0)");
_Static_assert(REFLEX_TIMG0_WDTCONFIG0_REG == (uint32_t)(TIMG_WDTCONFIG0_REG(0)),
               "REFLEX_TIMG0_WDTCONFIG0_REG diverges from TIMG_WDTCONFIG0_REG(0)");
_Static_assert(REFLEX_TIMG1_WDTCONFIG0_REG == (uint32_t)(TIMG_WDTCONFIG0_REG(1)),
               "REFLEX_TIMG1_WDTCONFIG0_REG diverges from TIMG_WDTCONFIG0_REG(1)");
_Static_assert(REFLEX_TIMG1_WDTWPROTECT_REG == (uint32_t)(TIMG_WDTWPROTECT_REG(1)),
               "REFLEX_TIMG1_WDTWPROTECT_REG diverges from TIMG_WDTWPROTECT_REG(1)");
_Static_assert(REFLEX_TIMG_WDT_EN == (uint32_t)(TIMG_WDT_EN),
               "REFLEX_TIMG_WDT_EN diverges from TIMG_WDT_EN");
_Static_assert(REFLEX_LP_AON_STORE0_REG == (uint32_t)(LP_AON_STORE0_REG),
               "REFLEX_LP_AON_STORE0_REG diverges from LP_AON_STORE0_REG");
_Static_assert(REFLEX_LP_AON_SYS_CFG_REG == (uint32_t)(LP_AON_SYS_CFG_REG),
               "REFLEX_LP_AON_SYS_CFG_REG diverges from LP_AON_SYS_CFG_REG");
_Static_assert(REFLEX_LP_AON_HPSYS_SW_RESET == (uint32_t)(LP_AON_HPSYS_SW_RESET),
               "REFLEX_LP_AON_HPSYS_SW_RESET diverges from LP_AON_HPSYS_SW_RESET");
_Static_assert(REFLEX_LP_ANA_INT_ENA_REG == (uint32_t)(LP_ANALOG_PERI_LP_ANA_LP_INT_ENA_REG),
               "REFLEX_LP_ANA_INT_ENA_REG diverges from LP_ANALOG_PERI_LP_ANA_LP_INT_ENA_REG");
_Static_assert(REFLEX_LP_ANA_INT_CLR_REG == (uint32_t)(LP_ANALOG_PERI_LP_ANA_LP_INT_CLR_REG),
               "REFLEX_LP_ANA_INT_CLR_REG diverges from LP_ANALOG_PERI_LP_ANA_LP_INT_CLR_REG");
_Static_assert(
    REFLEX_LP_ANA_BOD_MODE0_INT_ENA == (uint32_t)(LP_ANALOG_PERI_LP_ANA_BOD_MODE0_LP_INT_ENA),
    "REFLEX_LP_ANA_BOD_MODE0_INT_ENA diverges from LP_ANALOG_PERI_LP_ANA_BOD_MODE0_LP_INT_ENA");
_Static_assert(
    REFLEX_LP_ANA_BOD_MODE0_INT_CLR == (uint32_t)(LP_ANALOG_PERI_LP_ANA_BOD_MODE0_LP_INT_CLR),
    "REFLEX_LP_ANA_BOD_MODE0_INT_CLR diverges from LP_ANALOG_PERI_LP_ANA_BOD_MODE0_LP_INT_CLR");
_Static_assert(REFLEX_PMU_HP_INT_ENA_REG == (uint32_t)(PMU_HP_INT_ENA_REG),
               "REFLEX_PMU_HP_INT_ENA_REG diverges from PMU_HP_INT_ENA_REG");
_Static_assert(REFLEX_PMU_SOC_WAKEUP_INT_ENA == (uint32_t)(PMU_SOC_WAKEUP_INT_ENA),
               "REFLEX_PMU_SOC_WAKEUP_INT_ENA diverges from PMU_SOC_WAKEUP_INT_ENA");
_Static_assert(REFLEX_PMU_SOC_SLEEP_REJECT_INT_ENA == (uint32_t)(PMU_SOC_SLEEP_REJECT_INT_ENA),
               "REFLEX_PMU_SOC_SLEEP_REJECT_INT_ENA diverges from PMU_SOC_SLEEP_REJECT_INT_ENA");
_Static_assert(
    REFLEX_ASSIST_DEBUG_CORE_0_RCD_EN_REG == (uint32_t)(ASSIST_DEBUG_CORE_0_RCD_EN_REG),
    "REFLEX_ASSIST_DEBUG_CORE_0_RCD_EN_REG diverges from ASSIST_DEBUG_CORE_0_RCD_EN_REG");
_Static_assert(
    REFLEX_ASSIST_DEBUG_CORE_0_RCD_RECORDEN == (uint32_t)(ASSIST_DEBUG_CORE_0_RCD_RECORDEN),
    "REFLEX_ASSIST_DEBUG_CORE_0_RCD_RECORDEN diverges from ASSIST_DEBUG_CORE_0_RCD_RECORDEN");
_Static_assert(
    REFLEX_ASSIST_DEBUG_CORE_0_RCD_PDEBUGEN == (uint32_t)(ASSIST_DEBUG_CORE_0_RCD_PDEBUGEN),
    "REFLEX_ASSIST_DEBUG_CORE_0_RCD_PDEBUGEN diverges from ASSIST_DEBUG_CORE_0_RCD_PDEBUGEN");
_Static_assert(REFLEX_ASSIST_DEBUG_MONTR_ENA_REG == (uint32_t)(ASSIST_DEBUG_CORE_0_INTR_ENA_REG),
               "REFLEX_ASSIST_DEBUG_MONTR_ENA_REG diverges from ASSIST_DEBUG_CORE_0_INTR_ENA_REG");
_Static_assert(
    REFLEX_ASSIST_DEBUG_SP_SPILL_MIN_ENA == (uint32_t)(ASSIST_DEBUG_CORE_0_SP_SPILL_MIN_ENA),
    "REFLEX_ASSIST_DEBUG_SP_SPILL_MIN_ENA diverges from ASSIST_DEBUG_CORE_0_SP_SPILL_MIN_ENA");
_Static_assert(
    REFLEX_ASSIST_DEBUG_SP_SPILL_MAX_ENA == (uint32_t)(ASSIST_DEBUG_CORE_0_SP_SPILL_MAX_ENA),
    "REFLEX_ASSIST_DEBUG_SP_SPILL_MAX_ENA diverges from ASSIST_DEBUG_CORE_0_SP_SPILL_MAX_ENA");
_Static_assert(REFLEX_PCR_ASSIST_CONF_REG == (uint32_t)(PCR_ASSIST_CONF_REG),
               "REFLEX_PCR_ASSIST_CONF_REG diverges from PCR_ASSIST_CONF_REG");
_Static_assert(REFLEX_PCR_ASSIST_CLK_EN == (uint32_t)(PCR_ASSIST_CLK_EN),
               "REFLEX_PCR_ASSIST_CLK_EN diverges from PCR_ASSIST_CLK_EN");
_Static_assert(REFLEX_PCR_ASSIST_RST_EN == (uint32_t)(PCR_ASSIST_RST_EN),
               "REFLEX_PCR_ASSIST_RST_EN diverges from PCR_ASSIST_RST_EN");
_Static_assert(REFLEX_EXTMEM_L1_CACHE_CTRL_REG == (uint32_t)(EXTMEM_L1_CACHE_CTRL_REG),
               "REFLEX_EXTMEM_L1_CACHE_CTRL_REG diverges from EXTMEM_L1_CACHE_CTRL_REG");
_Static_assert(REFLEX_EXTMEM_L1_CACHE_SHUT_IBUS == (uint32_t)(EXTMEM_L1_CACHE_SHUT_IBUS),
               "REFLEX_EXTMEM_L1_CACHE_SHUT_IBUS diverges from EXTMEM_L1_CACHE_SHUT_IBUS");
_Static_assert(REFLEX_EXTMEM_L1_CACHE_SHUT_DBUS == (uint32_t)(EXTMEM_L1_CACHE_SHUT_DBUS),
               "REFLEX_EXTMEM_L1_CACHE_SHUT_DBUS diverges from EXTMEM_L1_CACHE_SHUT_DBUS");
_Static_assert(REFLEX_SPI_MEM_MMU_ITEM_CONTENT_REG == (uint32_t)(SPI_MEM_MMU_ITEM_CONTENT_REG(0)),
               "REFLEX_SPI_MEM_MMU_ITEM_CONTENT_REG diverges from SPI_MEM_MMU_ITEM_CONTENT_REG(0)");
_Static_assert(REFLEX_SPI_MEM_MMU_ITEM_INDEX_REG == (uint32_t)(SPI_MEM_MMU_ITEM_INDEX_REG(0)),
               "REFLEX_SPI_MEM_MMU_ITEM_INDEX_REG diverges from SPI_MEM_MMU_ITEM_INDEX_REG(0)");
_Static_assert(REFLEX_SPI_MEM_MMU_POWER_CTRL_REG == (uint32_t)(SPI_MEM_MMU_POWER_CTRL_REG(0)),
               "REFLEX_SPI_MEM_MMU_POWER_CTRL_REG diverges from SPI_MEM_MMU_POWER_CTRL_REG(0)");
_Static_assert(REFLEX_PMU_SLP_WAKEUP_STATUS0_REG == (uint32_t)(PMU_SLP_WAKEUP_STATUS0_REG),
               "REFLEX_PMU_SLP_WAKEUP_STATUS0_REG diverges from PMU_SLP_WAKEUP_STATUS0_REG");
_Static_assert(REFLEX_LP_AON_STORE1_REG == (uint32_t)(LP_AON_STORE1_REG),
               "REFLEX_LP_AON_STORE1_REG diverges from LP_AON_STORE1_REG");
_Static_assert(REFLEX_DR_REG_SYSTIMER_BASE == (uint32_t)(DR_REG_SYSTIMER_BASE),
               "REFLEX_DR_REG_SYSTIMER_BASE diverges from DR_REG_SYSTIMER_BASE");
_Static_assert(REFLEX_SYSTIMER_UNIT0_OP_REG == (uint32_t)(SYSTIMER_UNIT0_OP_REG),
               "REFLEX_SYSTIMER_UNIT0_OP_REG diverges from SYSTIMER_UNIT0_OP_REG");
_Static_assert(REFLEX_SYSTIMER_UNIT0_VALUE_LO_REG == (uint32_t)(SYSTIMER_UNIT0_VALUE_LO_REG),
               "REFLEX_SYSTIMER_UNIT0_VALUE_LO_REG diverges from SYSTIMER_UNIT0_VALUE_LO_REG");
_Static_assert(REFLEX_SYSTIMER_UNIT0_UPDATE == (uint32_t)(SYSTIMER_TIMER_UNIT0_UPDATE),
               "REFLEX_SYSTIMER_UNIT0_UPDATE diverges from SYSTIMER_TIMER_UNIT0_UPDATE");
_Static_assert(REFLEX_SYSTIMER_UNIT0_VALUE_VALID == (uint32_t)(SYSTIMER_TIMER_UNIT0_VALUE_VALID),
               "REFLEX_SYSTIMER_UNIT0_VALUE_VALID diverges from SYSTIMER_TIMER_UNIT0_VALUE_VALID");
_Static_assert(REFLEX_DR_REG_USB_SERIAL_JTAG_BASE == (uint32_t)(DR_REG_USB_SERIAL_JTAG_BASE),
               "REFLEX_DR_REG_USB_SERIAL_JTAG_BASE diverges from DR_REG_USB_SERIAL_JTAG_BASE");
_Static_assert(REFLEX_USJ_EP1_REG == (uint32_t)(USB_SERIAL_JTAG_EP1_REG),
               "REFLEX_USJ_EP1_REG diverges from USB_SERIAL_JTAG_EP1_REG");
_Static_assert(REFLEX_USJ_EP1_CONF_REG == (uint32_t)(USB_SERIAL_JTAG_EP1_CONF_REG),
               "REFLEX_USJ_EP1_CONF_REG diverges from USB_SERIAL_JTAG_EP1_CONF_REG");
_Static_assert(REFLEX_USJ_INT_RAW_REG == (uint32_t)(USB_SERIAL_JTAG_INT_RAW_REG),
               "REFLEX_USJ_INT_RAW_REG diverges from USB_SERIAL_JTAG_INT_RAW_REG");
_Static_assert(REFLEX_USJ_INT_ST_REG == (uint32_t)(USB_SERIAL_JTAG_INT_ST_REG),
               "REFLEX_USJ_INT_ST_REG diverges from USB_SERIAL_JTAG_INT_ST_REG");
_Static_assert(REFLEX_USJ_INT_ENA_REG == (uint32_t)(USB_SERIAL_JTAG_INT_ENA_REG),
               "REFLEX_USJ_INT_ENA_REG diverges from USB_SERIAL_JTAG_INT_ENA_REG");
_Static_assert(REFLEX_USJ_INT_CLR_REG == (uint32_t)(USB_SERIAL_JTAG_INT_CLR_REG),
               "REFLEX_USJ_INT_CLR_REG diverges from USB_SERIAL_JTAG_INT_CLR_REG");
_Static_assert(
    REFLEX_USJ_OUT_EP_DATA_AVAIL == (uint32_t)(USB_SERIAL_JTAG_SERIAL_OUT_EP_DATA_AVAIL),
    "REFLEX_USJ_OUT_EP_DATA_AVAIL diverges from USB_SERIAL_JTAG_SERIAL_OUT_EP_DATA_AVAIL");
_Static_assert(
    REFLEX_USJ_OUT_RECV_PKT_INT == (uint32_t)(USB_SERIAL_JTAG_SERIAL_OUT_RECV_PKT_INT_ENA),
    "REFLEX_USJ_OUT_RECV_PKT_INT diverges from USB_SERIAL_JTAG_SERIAL_OUT_RECV_PKT_INT_ENA");
_Static_assert(REFLEX_DR_REG_LEDC_BASE == (uint32_t)(DR_REG_LEDC_BASE),
               "REFLEX_DR_REG_LEDC_BASE diverges from DR_REG_LEDC_BASE");
_Static_assert(REFLEX_LEDC_CH0_CONF0_REG == (uint32_t)(LEDC_CH0_CONF0_REG),
               "REFLEX_LEDC_CH0_CONF0_REG diverges from LEDC_CH0_CONF0_REG");
_Static_assert(REFLEX_LEDC_CH0_HPOINT_REG == (uint32_t)(LEDC_CH0_HPOINT_REG),
               "REFLEX_LEDC_CH0_HPOINT_REG diverges from LEDC_CH0_HPOINT_REG");
_Static_assert(REFLEX_LEDC_CH0_DUTY_REG == (uint32_t)(LEDC_CH0_DUTY_REG),
               "REFLEX_LEDC_CH0_DUTY_REG diverges from LEDC_CH0_DUTY_REG");
_Static_assert(REFLEX_LEDC_CH0_CONF1_REG == (uint32_t)(LEDC_CH0_CONF1_REG),
               "REFLEX_LEDC_CH0_CONF1_REG diverges from LEDC_CH0_CONF1_REG");
_Static_assert(REFLEX_LEDC_TIMER0_CONF_REG == (uint32_t)(LEDC_TIMER0_CONF_REG),
               "REFLEX_LEDC_TIMER0_CONF_REG diverges from LEDC_TIMER0_CONF_REG");
_Static_assert(REFLEX_LEDC_SIG_OUT_EN == (uint32_t)(LEDC_SIG_OUT_EN_CH0),
               "REFLEX_LEDC_SIG_OUT_EN diverges from LEDC_SIG_OUT_EN_CH0");
_Static_assert(REFLEX_LEDC_CH_PARA_UP == (uint32_t)(LEDC_PARA_UP_CH0),
               "REFLEX_LEDC_CH_PARA_UP diverges from LEDC_PARA_UP_CH0");
_Static_assert(REFLEX_LEDC_DUTY_START == (uint32_t)(LEDC_DUTY_START_CH0),
               "REFLEX_LEDC_DUTY_START diverges from LEDC_DUTY_START_CH0");
_Static_assert(REFLEX_LEDC_TIMER_RST == (uint32_t)(LEDC_TIMER0_RST),
               "REFLEX_LEDC_TIMER_RST diverges from LEDC_TIMER0_RST");
_Static_assert(REFLEX_LEDC_TIMER_PARA_UP == (uint32_t)(LEDC_TIMER0_PARA_UP),
               "REFLEX_LEDC_TIMER_PARA_UP diverges from LEDC_TIMER0_PARA_UP");
_Static_assert(REFLEX_PCR_LEDC_CONF_REG == (uint32_t)(PCR_LEDC_CONF_REG),
               "REFLEX_PCR_LEDC_CONF_REG diverges from PCR_LEDC_CONF_REG");
_Static_assert(REFLEX_PCR_LEDC_SCLK_CONF_REG == (uint32_t)(PCR_LEDC_SCLK_CONF_REG),
               "REFLEX_PCR_LEDC_SCLK_CONF_REG diverges from PCR_LEDC_SCLK_CONF_REG");
_Static_assert(REFLEX_PCR_LEDC_CLK_EN == (uint32_t)(PCR_LEDC_CLK_EN),
               "REFLEX_PCR_LEDC_CLK_EN diverges from PCR_LEDC_CLK_EN");
_Static_assert(REFLEX_PCR_LEDC_RST_EN == (uint32_t)(PCR_LEDC_RST_EN),
               "REFLEX_PCR_LEDC_RST_EN diverges from PCR_LEDC_RST_EN");
_Static_assert(REFLEX_PCR_LEDC_SCLK_EN == (uint32_t)(PCR_LEDC_SCLK_EN),
               "REFLEX_PCR_LEDC_SCLK_EN diverges from PCR_LEDC_SCLK_EN");
_Static_assert(REFLEX_DR_REG_PCNT_BASE == (uint32_t)(DR_REG_PCNT_BASE),
               "REFLEX_DR_REG_PCNT_BASE diverges from DR_REG_PCNT_BASE");
_Static_assert(REFLEX_PCNT_U0_CONF0_REG == (uint32_t)(PCNT_U0_CONF0_REG),
               "REFLEX_PCNT_U0_CONF0_REG diverges from PCNT_U0_CONF0_REG");
_Static_assert(REFLEX_PCNT_U0_CONF1_REG == (uint32_t)(PCNT_U0_CONF1_REG),
               "REFLEX_PCNT_U0_CONF1_REG diverges from PCNT_U0_CONF1_REG");
_Static_assert(REFLEX_PCNT_U0_CONF2_REG == (uint32_t)(PCNT_U0_CONF2_REG),
               "REFLEX_PCNT_U0_CONF2_REG diverges from PCNT_U0_CONF2_REG");
_Static_assert(REFLEX_PCNT_U0_CNT_REG == (uint32_t)(PCNT_U0_CNT_REG),
               "REFLEX_PCNT_U0_CNT_REG diverges from PCNT_U0_CNT_REG");
_Static_assert(REFLEX_PCNT_CTRL_REG == (uint32_t)(PCNT_CTRL_REG),
               "REFLEX_PCNT_CTRL_REG diverges from PCNT_CTRL_REG");
_Static_assert(REFLEX_PCNT_FILTER_EN == (uint32_t)(PCNT_FILTER_EN_U0),
               "REFLEX_PCNT_FILTER_EN diverges from PCNT_FILTER_EN_U0");
_Static_assert(REFLEX_PCNT_THR_ZERO_EN == (uint32_t)(PCNT_THR_ZERO_EN_U0),
               "REFLEX_PCNT_THR_ZERO_EN diverges from PCNT_THR_ZERO_EN_U0");
_Static_assert(REFLEX_PCNT_THR_H_LIM_EN == (uint32_t)(PCNT_THR_H_LIM_EN_U0),
               "REFLEX_PCNT_THR_H_LIM_EN diverges from PCNT_THR_H_LIM_EN_U0");
_Static_assert(REFLEX_PCNT_THR_L_LIM_EN == (uint32_t)(PCNT_THR_L_LIM_EN_U0),
               "REFLEX_PCNT_THR_L_LIM_EN diverges from PCNT_THR_L_LIM_EN_U0");
_Static_assert(REFLEX_PCNT_THR_THRES0_EN == (uint32_t)(PCNT_THR_THRES0_EN_U0),
               "REFLEX_PCNT_THR_THRES0_EN diverges from PCNT_THR_THRES0_EN_U0");
_Static_assert(REFLEX_PCNT_THR_THRES1_EN == (uint32_t)(PCNT_THR_THRES1_EN_U0),
               "REFLEX_PCNT_THR_THRES1_EN diverges from PCNT_THR_THRES1_EN_U0");
_Static_assert(REFLEX_PCNT_CNT_RST_U0 == (uint32_t)(PCNT_PULSE_CNT_RST_U0),
               "REFLEX_PCNT_CNT_RST_U0 diverges from PCNT_PULSE_CNT_RST_U0");
_Static_assert(REFLEX_PCNT_CNT_PAUSE_U0 == (uint32_t)(PCNT_CNT_PAUSE_U0),
               "REFLEX_PCNT_CNT_PAUSE_U0 diverges from PCNT_CNT_PAUSE_U0");
_Static_assert(REFLEX_PCR_PCNT_CONF_REG == (uint32_t)(PCR_PCNT_CONF_REG),
               "REFLEX_PCR_PCNT_CONF_REG diverges from PCR_PCNT_CONF_REG");
_Static_assert(REFLEX_PCR_PCNT_CLK_EN == (uint32_t)(PCR_PCNT_CLK_EN),
               "REFLEX_PCR_PCNT_CLK_EN diverges from PCR_PCNT_CLK_EN");
_Static_assert(REFLEX_PCR_PCNT_RST_EN == (uint32_t)(PCR_PCNT_RST_EN),
               "REFLEX_PCR_PCNT_RST_EN diverges from PCR_PCNT_RST_EN");
_Static_assert(REFLEX_DR_REG_RMT_BASE == (uint32_t)(DR_REG_RMT_BASE),
               "REFLEX_DR_REG_RMT_BASE diverges from DR_REG_RMT_BASE");
_Static_assert(REFLEX_RMT_CH0_TX_CONF0_REG == (uint32_t)(RMT_CH0CONF0_REG),
               "REFLEX_RMT_CH0_TX_CONF0_REG diverges from RMT_CH0CONF0_REG");
_Static_assert(REFLEX_RMT_CH0DATA_REG == (uint32_t)(RMT_CH0DATA_REG),
               "REFLEX_RMT_CH0DATA_REG diverges from RMT_CH0DATA_REG");
_Static_assert(REFLEX_RMT_CH0_TX_LIM_REG == (uint32_t)(RMT_CH0_TX_LIM_REG),
               "REFLEX_RMT_CH0_TX_LIM_REG diverges from RMT_CH0_TX_LIM_REG");
_Static_assert(REFLEX_RMT_SYS_CONF_REG == (uint32_t)(RMT_SYS_CONF_REG),
               "REFLEX_RMT_SYS_CONF_REG diverges from RMT_SYS_CONF_REG");
_Static_assert(REFLEX_RMT_INT_RAW_REG == (uint32_t)(RMT_INT_RAW_REG),
               "REFLEX_RMT_INT_RAW_REG diverges from RMT_INT_RAW_REG");
_Static_assert(REFLEX_RMT_INT_CLR_REG == (uint32_t)(RMT_INT_CLR_REG),
               "REFLEX_RMT_INT_CLR_REG diverges from RMT_INT_CLR_REG");
_Static_assert(REFLEX_RMT_TX_START == (uint32_t)(RMT_TX_START_CH0),
               "REFLEX_RMT_TX_START diverges from RMT_TX_START_CH0");
_Static_assert(REFLEX_RMT_MEM_RD_RST == (uint32_t)(RMT_MEM_RD_RST_CH0),
               "REFLEX_RMT_MEM_RD_RST diverges from RMT_MEM_RD_RST_CH0");
_Static_assert(REFLEX_RMT_APB_MEM_RST == (uint32_t)(RMT_APB_MEM_RST_CH0),
               "REFLEX_RMT_APB_MEM_RST diverges from RMT_APB_MEM_RST_CH0");
_Static_assert(REFLEX_RMT_TX_STOP == (uint32_t)(RMT_TX_STOP_CH0),
               "REFLEX_RMT_TX_STOP diverges from RMT_TX_STOP_CH0");
_Static_assert(REFLEX_RMT_IDLE_OUT_EN == (uint32_t)(RMT_IDLE_OUT_EN_CH0),
               "REFLEX_RMT_IDLE_OUT_EN diverges from RMT_IDLE_OUT_EN_CH0");
_Static_assert(REFLEX_RMT_MEM_TX_WRAP_EN == (uint32_t)(RMT_MEM_TX_WRAP_EN_CH0),
               "REFLEX_RMT_MEM_TX_WRAP_EN diverges from RMT_MEM_TX_WRAP_EN_CH0");
_Static_assert(REFLEX_RMT_CARRIER_EFF_EN == (uint32_t)(RMT_CARRIER_EFF_EN_CH0),
               "REFLEX_RMT_CARRIER_EFF_EN diverges from RMT_CARRIER_EFF_EN_CH0");
_Static_assert(REFLEX_RMT_CARRIER_OUT_LV == (uint32_t)(RMT_CARRIER_OUT_LV_CH0),
               "REFLEX_RMT_CARRIER_OUT_LV diverges from RMT_CARRIER_OUT_LV_CH0");
_Static_assert(REFLEX_RMT_LOOP_STOP_EN == (uint32_t)(RMT_LOOP_STOP_EN_CH0),
               "REFLEX_RMT_LOOP_STOP_EN diverges from RMT_LOOP_STOP_EN_CH0");
_Static_assert(REFLEX_RMT_CONF_UPDATE == (uint32_t)(RMT_CONF_UPDATE_CH0),
               "REFLEX_RMT_CONF_UPDATE diverges from RMT_CONF_UPDATE_CH0");
_Static_assert(REFLEX_RMT_APB_FIFO_MASK == (uint32_t)(RMT_APB_FIFO_MASK),
               "REFLEX_RMT_APB_FIFO_MASK diverges from RMT_APB_FIFO_MASK");
_Static_assert(REFLEX_RMT_SCLK_ACTIVE == (uint32_t)(RMT_RMT_SCLK_ACTIVE),
               "REFLEX_RMT_SCLK_ACTIVE diverges from RMT_RMT_SCLK_ACTIVE");
_Static_assert(REFLEX_RMT_CH0_TX_END_INT_RAW == (uint32_t)(RMT_CH0_TX_END_INT_RAW),
               "REFLEX_RMT_CH0_TX_END_INT_RAW diverges from RMT_CH0_TX_END_INT_RAW");
_Static_assert(REFLEX_PCR_RMT_CONF_REG == (uint32_t)(PCR_RMT_CONF_REG),
               "REFLEX_PCR_RMT_CONF_REG diverges from PCR_RMT_CONF_REG");
_Static_assert(REFLEX_PCR_RMT_SCLK_CONF_REG == (uint32_t)(PCR_RMT_SCLK_CONF_REG),
               "REFLEX_PCR_RMT_SCLK_CONF_REG diverges from PCR_RMT_SCLK_CONF_REG");
_Static_assert(REFLEX_PCR_RMT_CLK_EN == (uint32_t)(PCR_RMT_CLK_EN),
               "REFLEX_PCR_RMT_CLK_EN diverges from PCR_RMT_CLK_EN");
_Static_assert(REFLEX_PCR_RMT_RST_EN == (uint32_t)(PCR_RMT_RST_EN),
               "REFLEX_PCR_RMT_RST_EN diverges from PCR_RMT_RST_EN");
_Static_assert(REFLEX_PCR_RMT_SCLK_EN == (uint32_t)(PCR_RMT_SCLK_EN),
               "REFLEX_PCR_RMT_SCLK_EN diverges from PCR_RMT_SCLK_EN");
_Static_assert(REFLEX_SPI_MEM_MMU_PAGE_SIZE == (uint32_t)(SPI_MEM_MMU_PAGE_SIZE),
               "REFLEX_SPI_MEM_MMU_PAGE_SIZE diverges from SPI_MEM_MMU_PAGE_SIZE");
_Static_assert(REFLEX_LP_WDT_STG_MASK == (uint32_t)(LP_WDT_WDT_STG0_V),
               "REFLEX_LP_WDT_STG_MASK diverges from LP_WDT_WDT_STG0_V");
_Static_assert(REFLEX_LP_WDT_RESET_LEN_MASK == (uint32_t)(LP_WDT_WDT_SYS_RESET_LENGTH_V),
               "REFLEX_LP_WDT_RESET_LEN_MASK diverges from LP_WDT_WDT_SYS_RESET_LENGTH_V");
_Static_assert(REFLEX_LEDC_TIMER_SEL_MASK == (uint32_t)(LEDC_TIMER_SEL_CH0_V),
               "REFLEX_LEDC_TIMER_SEL_MASK diverges from LEDC_TIMER_SEL_CH0_V");
_Static_assert(REFLEX_LEDC_DUTY_MASK == (uint32_t)(LEDC_DUTY_CH0_V),
               "REFLEX_LEDC_DUTY_MASK diverges from LEDC_DUTY_CH0_V");
_Static_assert(REFLEX_LEDC_DUTY_RES_MASK == (uint32_t)(LEDC_TIMER0_DUTY_RES_V),
               "REFLEX_LEDC_DUTY_RES_MASK diverges from LEDC_TIMER0_DUTY_RES_V");
_Static_assert(REFLEX_LEDC_CLK_DIV_MASK == (uint32_t)(LEDC_CLK_DIV_TIMER0_V),
               "REFLEX_LEDC_CLK_DIV_MASK diverges from LEDC_CLK_DIV_TIMER0_V");
_Static_assert(REFLEX_PCR_LEDC_SCLK_SEL_MASK == (uint32_t)(PCR_LEDC_SCLK_SEL_V),
               "REFLEX_PCR_LEDC_SCLK_SEL_MASK diverges from PCR_LEDC_SCLK_SEL_V");
_Static_assert(REFLEX_PCNT_MODE_MASK == (uint32_t)(PCNT_CH0_POS_MODE_U0_V),
               "REFLEX_PCNT_MODE_MASK diverges from PCNT_CH0_POS_MODE_U0_V");
_Static_assert(REFLEX_PCNT_LIM_MASK == (uint32_t)(PCNT_CNT_H_LIM_U0_V),
               "REFLEX_PCNT_LIM_MASK diverges from PCNT_CNT_H_LIM_U0_V");
_Static_assert(REFLEX_PCNT_CNT_MASK == (uint32_t)(PCNT_PULSE_CNT_U0_V),
               "REFLEX_PCNT_CNT_MASK diverges from PCNT_PULSE_CNT_U0_V");
_Static_assert(REFLEX_RMT_DIV_CNT_MASK == (uint32_t)(RMT_DIV_CNT_CH0_V),
               "REFLEX_RMT_DIV_CNT_MASK diverges from RMT_DIV_CNT_CH0_V");
_Static_assert(REFLEX_RMT_MEM_SIZE_MASK == (uint32_t)(RMT_MEM_SIZE_CH0_V),
               "REFLEX_RMT_MEM_SIZE_MASK diverges from RMT_MEM_SIZE_CH0_V");
_Static_assert(REFLEX_RMT_SCLK_DIV_NUM_MASK == (uint32_t)(RMT_RMT_SCLK_DIV_NUM_V),
               "REFLEX_RMT_SCLK_DIV_NUM_MASK diverges from RMT_RMT_SCLK_DIV_NUM_V");
_Static_assert(REFLEX_RMT_SCLK_SEL_MASK == (uint32_t)(RMT_RMT_SCLK_SEL_V),
               "REFLEX_RMT_SCLK_SEL_MASK diverges from RMT_RMT_SCLK_SEL_V");
_Static_assert(REFLEX_RMT_TX_LIM_MASK == (uint32_t)(RMT_TX_LIM_CH0_V),
               "REFLEX_RMT_TX_LIM_MASK diverges from RMT_TX_LIM_CH0_V");
_Static_assert(REFLEX_PCR_RMT_SCLK_DIV_A_MASK == (uint32_t)(PCR_RMT_SCLK_DIV_A_V),
               "REFLEX_PCR_RMT_SCLK_DIV_A_MASK diverges from PCR_RMT_SCLK_DIV_A_V");
_Static_assert(REFLEX_PCR_RMT_SCLK_DIV_B_MASK == (uint32_t)(PCR_RMT_SCLK_DIV_B_V),
               "REFLEX_PCR_RMT_SCLK_DIV_B_MASK diverges from PCR_RMT_SCLK_DIV_B_V");
_Static_assert(REFLEX_PCR_RMT_SCLK_DIV_NUM_MASK == (uint32_t)(PCR_RMT_SCLK_DIV_NUM_V),
               "REFLEX_PCR_RMT_SCLK_DIV_NUM_MASK diverges from PCR_RMT_SCLK_DIV_NUM_V");
_Static_assert(REFLEX_PCR_RMT_SCLK_SEL_MASK == (uint32_t)(PCR_RMT_SCLK_SEL_V),
               "REFLEX_PCR_RMT_SCLK_SEL_MASK diverges from PCR_RMT_SCLK_SEL_V");
_Static_assert(REFLEX_SPI_MEM_MMU_PAGE_SIZE_S == (uint32_t)(SPI_MEM_MMU_PAGE_SIZE_S),
               "REFLEX_SPI_MEM_MMU_PAGE_SIZE_S diverges from SPI_MEM_MMU_PAGE_SIZE_S");
_Static_assert(REFLEX_LP_WDT_STG0_S == (uint32_t)(LP_WDT_WDT_STG0_S),
               "REFLEX_LP_WDT_STG0_S diverges from LP_WDT_WDT_STG0_S");
_Static_assert(REFLEX_LP_WDT_SYS_RESET_LEN_S == (uint32_t)(LP_WDT_WDT_SYS_RESET_LENGTH_S),
               "REFLEX_LP_WDT_SYS_RESET_LEN_S diverges from LP_WDT_WDT_SYS_RESET_LENGTH_S");
_Static_assert(REFLEX_LP_WDT_CPU_RESET_LEN_S == (uint32_t)(LP_WDT_WDT_CPU_RESET_LENGTH_S),
               "REFLEX_LP_WDT_CPU_RESET_LEN_S diverges from LP_WDT_WDT_CPU_RESET_LENGTH_S");
_Static_assert(REFLEX_LEDC_TIMER_SEL_S == (uint32_t)(LEDC_TIMER_SEL_CH0_S),
               "REFLEX_LEDC_TIMER_SEL_S diverges from LEDC_TIMER_SEL_CH0_S");
_Static_assert(REFLEX_LEDC_DUTY_S == (uint32_t)(LEDC_DUTY_CH0_S),
               "REFLEX_LEDC_DUTY_S diverges from LEDC_DUTY_CH0_S");
_Static_assert(REFLEX_LEDC_DUTY_RES_S == (uint32_t)(LEDC_TIMER0_DUTY_RES_S),
               "REFLEX_LEDC_DUTY_RES_S diverges from LEDC_TIMER0_DUTY_RES_S");
_Static_assert(REFLEX_LEDC_CLK_DIV_S == (uint32_t)(LEDC_CLK_DIV_TIMER0_S),
               "REFLEX_LEDC_CLK_DIV_S diverges from LEDC_CLK_DIV_TIMER0_S");
_Static_assert(REFLEX_PCR_LEDC_SCLK_SEL_S == (uint32_t)(PCR_LEDC_SCLK_SEL_S),
               "REFLEX_PCR_LEDC_SCLK_SEL_S diverges from PCR_LEDC_SCLK_SEL_S");
_Static_assert(REFLEX_PCNT_CH0_POS_MODE_S == (uint32_t)(PCNT_CH0_POS_MODE_U0_S),
               "REFLEX_PCNT_CH0_POS_MODE_S diverges from PCNT_CH0_POS_MODE_U0_S");
_Static_assert(REFLEX_PCNT_CH0_NEG_MODE_S == (uint32_t)(PCNT_CH0_NEG_MODE_U0_S),
               "REFLEX_PCNT_CH0_NEG_MODE_S diverges from PCNT_CH0_NEG_MODE_U0_S");
_Static_assert(REFLEX_PCNT_CH0_HCTRL_MODE_S == (uint32_t)(PCNT_CH0_HCTRL_MODE_U0_S),
               "REFLEX_PCNT_CH0_HCTRL_MODE_S diverges from PCNT_CH0_HCTRL_MODE_U0_S");
_Static_assert(REFLEX_PCNT_CH0_LCTRL_MODE_S == (uint32_t)(PCNT_CH0_LCTRL_MODE_U0_S),
               "REFLEX_PCNT_CH0_LCTRL_MODE_S diverges from PCNT_CH0_LCTRL_MODE_U0_S");
_Static_assert(REFLEX_PCNT_CNT_H_LIM_S == (uint32_t)(PCNT_CNT_H_LIM_U0_S),
               "REFLEX_PCNT_CNT_H_LIM_S diverges from PCNT_CNT_H_LIM_U0_S");
_Static_assert(REFLEX_PCNT_CNT_L_LIM_S == (uint32_t)(PCNT_CNT_L_LIM_U0_S),
               "REFLEX_PCNT_CNT_L_LIM_S diverges from PCNT_CNT_L_LIM_U0_S");
_Static_assert(REFLEX_RMT_DIV_CNT_S == (uint32_t)(RMT_DIV_CNT_CH0_S),
               "REFLEX_RMT_DIV_CNT_S diverges from RMT_DIV_CNT_CH0_S");
_Static_assert(REFLEX_RMT_MEM_SIZE_S == (uint32_t)(RMT_MEM_SIZE_CH0_S),
               "REFLEX_RMT_MEM_SIZE_S diverges from RMT_MEM_SIZE_CH0_S");
_Static_assert(REFLEX_RMT_SCLK_DIV_NUM_S == (uint32_t)(RMT_RMT_SCLK_DIV_NUM_S),
               "REFLEX_RMT_SCLK_DIV_NUM_S diverges from RMT_RMT_SCLK_DIV_NUM_S");
_Static_assert(REFLEX_RMT_SCLK_SEL_S == (uint32_t)(RMT_RMT_SCLK_SEL_S),
               "REFLEX_RMT_SCLK_SEL_S diverges from RMT_RMT_SCLK_SEL_S");
_Static_assert(REFLEX_RMT_TX_LIM_S == (uint32_t)(RMT_TX_LIM_CH0_S),
               "REFLEX_RMT_TX_LIM_S diverges from RMT_TX_LIM_CH0_S");
_Static_assert(REFLEX_PCR_RMT_SCLK_DIV_A_S == (uint32_t)(PCR_RMT_SCLK_DIV_A_S),
               "REFLEX_PCR_RMT_SCLK_DIV_A_S diverges from PCR_RMT_SCLK_DIV_A_S");
_Static_assert(REFLEX_PCR_RMT_SCLK_DIV_B_S == (uint32_t)(PCR_RMT_SCLK_DIV_B_S),
               "REFLEX_PCR_RMT_SCLK_DIV_B_S diverges from PCR_RMT_SCLK_DIV_B_S");
_Static_assert(REFLEX_PCR_RMT_SCLK_DIV_NUM_S == (uint32_t)(PCR_RMT_SCLK_DIV_NUM_S),
               "REFLEX_PCR_RMT_SCLK_DIV_NUM_S diverges from PCR_RMT_SCLK_DIV_NUM_S");
_Static_assert(REFLEX_PCR_RMT_SCLK_SEL_S == (uint32_t)(PCR_RMT_SCLK_SEL_S),
               "REFLEX_PCR_RMT_SCLK_SEL_S diverges from PCR_RMT_SCLK_SEL_S");
_Static_assert(REFLEX_SOC_IRAM_LOW == (uint32_t)(SOC_IRAM_LOW),
               "REFLEX_SOC_IRAM_LOW diverges from SOC_IRAM_LOW");
_Static_assert(REFLEX_SOC_IRAM_HIGH == (uint32_t)(SOC_IRAM_HIGH),
               "REFLEX_SOC_IRAM_HIGH diverges from SOC_IRAM_HIGH");
_Static_assert(REFLEX_SOC_RTC_IRAM_LOW == (uint32_t)(SOC_RTC_IRAM_LOW),
               "REFLEX_SOC_RTC_IRAM_LOW diverges from SOC_RTC_IRAM_LOW");
_Static_assert(REFLEX_SOC_RTC_IRAM_HIGH == (uint32_t)(SOC_RTC_IRAM_HIGH),
               "REFLEX_SOC_RTC_IRAM_HIGH diverges from SOC_RTC_IRAM_HIGH");
_Static_assert(REFLEX_TIMG_WDT_WKEY_VALUE == (uint32_t)(TIMG_WDT_WKEY_VALUE),
               "REFLEX_TIMG_WDT_WKEY_VALUE diverges from TIMG_WDT_WKEY_VALUE");
_Static_assert(REFLEX_LEDC_LS_SIG_OUT0_IDX == (uint32_t)(LEDC_LS_SIG_OUT0_IDX),
               "REFLEX_LEDC_LS_SIG_OUT0_IDX diverges from LEDC_LS_SIG_OUT0_IDX");
_Static_assert(REFLEX_PCNT_SIG_CH0_IN0_IDX == (uint32_t)(PCNT_SIG_CH0_IN0_IDX),
               "REFLEX_PCNT_SIG_CH0_IN0_IDX diverges from PCNT_SIG_CH0_IN0_IDX");
_Static_assert(REFLEX_PCNT_CTRL_CH0_IN0_IDX == (uint32_t)(PCNT_CTRL_CH0_IN0_IDX),
               "REFLEX_PCNT_CTRL_CH0_IN0_IDX diverges from PCNT_CTRL_CH0_IN0_IDX");
_Static_assert(REFLEX_GPIO_MATRIX_CONST_ZERO_INPUT == (uint32_t)(GPIO_MATRIX_CONST_ZERO_INPUT),
               "REFLEX_GPIO_MATRIX_CONST_ZERO_INPUT diverges from GPIO_MATRIX_CONST_ZERO_INPUT");
_Static_assert(REFLEX_TIMG_WDT_WKEY == (uint32_t)(TIMG_WDT_WKEY_VALUE),
               "REFLEX_TIMG_WDT_WKEY diverges from TIMG_WDT_WKEY_VALUE");
_Static_assert(REFLEX_LP_WDT_WKEY == (uint32_t)(LP_WDT_WKEY_VALUE),
               "REFLEX_LP_WDT_WKEY diverges from LP_WDT_WKEY_VALUE");
_Static_assert(REFLEX_SIG_GPIO_OUT_IDX == (uint32_t)(SIG_GPIO_OUT_IDX),
               "REFLEX_SIG_GPIO_OUT_IDX diverges from SIG_GPIO_OUT_IDX");
_Static_assert(REFLEX_RMT_SIG_OUT0_IDX == (uint32_t)(RMT_SIG_OUT0_IDX),
               "REFLEX_RMT_SIG_OUT0_IDX diverges from RMT_SIG_OUT0_IDX");
_Static_assert(REFLEX_IO_MUX_MCU_SEL_V == (uint32_t)(MCU_SEL),
               "REFLEX_IO_MUX_MCU_SEL_V diverges from MCU_SEL");
_Static_assert(REFLEX_SOC_SYSTIMER_FIXED_DIVIDER == (uint32_t)(SOC_SYSTIMER_FIXED_DIVIDER),
               "REFLEX_SOC_SYSTIMER_FIXED_DIVIDER diverges from SOC_SYSTIMER_FIXED_DIVIDER");
_Static_assert(REFLEX_INTR_SRC_SYSTIMER_TARGET1 == (uint32_t)(ETS_SYSTIMER_TARGET1_INTR_SOURCE),
               "REFLEX_INTR_SRC_SYSTIMER_TARGET1 diverges from ETS_SYSTIMER_TARGET1_INTR_SOURCE");
_Static_assert(REFLEX_INTR_SRC_USB_SERIAL_JTAG == (uint32_t)(ETS_USB_SERIAL_JTAG_INTR_SOURCE),
               "REFLEX_INTR_SRC_USB_SERIAL_JTAG diverges from ETS_USB_SERIAL_JTAG_INTR_SOURCE");

/* Silence the unused-translation-unit warning. */
const int reflex_soc_bridge_ok = 1;
